package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class CaseArticle extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public CaseArticle() {}

    /**
     * element : ArticleLanguage of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ArticleLanguage__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ArticleLanguage","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ArticleLanguage__is_set = false;

    private java.lang.String ArticleLanguage;

    public java.lang.String getArticleLanguage() {
      return ArticleLanguage;
    }

    public void setArticleLanguage(java.lang.String ArticleLanguage) {
      this.ArticleLanguage = ArticleLanguage;
      ArticleLanguage__is_set = true;
    }

    /**
     * element : ArticleVersionNumber of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo ArticleVersionNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ArticleVersionNumber","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean ArticleVersionNumber__is_set = false;

    private java.lang.Integer ArticleVersionNumber;

    public java.lang.Integer getArticleVersionNumber() {
      return ArticleVersionNumber;
    }

    public void setArticleVersionNumber(java.lang.Integer ArticleVersionNumber) {
      this.ArticleVersionNumber = ArticleVersionNumber;
      ArticleVersionNumber__is_set = true;
    }

    /**
     * element : Case of type {urn:sobject.enterprise.soap.sforce.com}Case
     * java type: com.sforce.soap.enterprise.sobject.Case
     */
    private static final com.sforce.ws.bind.TypeInfo Case__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Case","urn:sobject.enterprise.soap.sforce.com","Case",0,1,true);

    private boolean Case__is_set = false;

    private com.sforce.soap.enterprise.sobject.Case Case;

    public com.sforce.soap.enterprise.sobject.Case getCase() {
      return Case;
    }

    public void setCase(com.sforce.soap.enterprise.sobject.Case Case) {
      this.Case = Case;
      Case__is_set = true;
    }

    /**
     * element : CaseId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CaseId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CaseId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CaseId__is_set = false;

    private java.lang.String CaseId;

    public java.lang.String getCaseId() {
      return CaseId;
    }

    public void setCaseId(java.lang.String CaseId) {
      this.CaseId = CaseId;
      CaseId__is_set = true;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : IsSharedByEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsSharedByEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsSharedByEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsSharedByEmail__is_set = false;

    private java.lang.Boolean IsSharedByEmail;

    public java.lang.Boolean getIsSharedByEmail() {
      return IsSharedByEmail;
    }

    public void setIsSharedByEmail(java.lang.Boolean IsSharedByEmail) {
      this.IsSharedByEmail = IsSharedByEmail;
      IsSharedByEmail__is_set = true;
    }

    /**
     * element : KnowledgeArticle of type {urn:sobject.enterprise.soap.sforce.com}FAQ__ka
     * java type: com.sforce.soap.enterprise.sobject.FAQ__ka
     */
    private static final com.sforce.ws.bind.TypeInfo KnowledgeArticle__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","KnowledgeArticle","urn:sobject.enterprise.soap.sforce.com","FAQ__ka",0,1,true);

    private boolean KnowledgeArticle__is_set = false;

    private com.sforce.soap.enterprise.sobject.FAQ__ka KnowledgeArticle;

    public com.sforce.soap.enterprise.sobject.FAQ__ka getKnowledgeArticle() {
      return KnowledgeArticle;
    }

    public void setKnowledgeArticle(com.sforce.soap.enterprise.sobject.FAQ__ka KnowledgeArticle) {
      this.KnowledgeArticle = KnowledgeArticle;
      KnowledgeArticle__is_set = true;
    }

    /**
     * element : KnowledgeArticleId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo KnowledgeArticleId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","KnowledgeArticleId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean KnowledgeArticleId__is_set = false;

    private java.lang.String KnowledgeArticleId;

    public java.lang.String getKnowledgeArticleId() {
      return KnowledgeArticleId;
    }

    public void setKnowledgeArticleId(java.lang.String KnowledgeArticleId) {
      this.KnowledgeArticleId = KnowledgeArticleId;
      KnowledgeArticleId__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "CaseArticle");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeString(__out, ArticleLanguage__typeInfo, ArticleLanguage, ArticleLanguage__is_set);
       __typeMapper.writeObject(__out, ArticleVersionNumber__typeInfo, ArticleVersionNumber, ArticleVersionNumber__is_set);
       __typeMapper.writeObject(__out, Case__typeInfo, Case, Case__is_set);
       __typeMapper.writeString(__out, CaseId__typeInfo, CaseId, CaseId__is_set);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeObject(__out, IsSharedByEmail__typeInfo, IsSharedByEmail, IsSharedByEmail__is_set);
       __typeMapper.writeObject(__out, KnowledgeArticle__typeInfo, KnowledgeArticle, KnowledgeArticle__is_set);
       __typeMapper.writeString(__out, KnowledgeArticleId__typeInfo, KnowledgeArticleId, KnowledgeArticleId__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, ArticleLanguage__typeInfo)) {
            setArticleLanguage(__typeMapper.readString(__in, ArticleLanguage__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ArticleVersionNumber__typeInfo)) {
            setArticleVersionNumber((java.lang.Integer)__typeMapper.readObject(__in, ArticleVersionNumber__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Case__typeInfo)) {
            setCase((com.sforce.soap.enterprise.sobject.Case)__typeMapper.readObject(__in, Case__typeInfo, com.sforce.soap.enterprise.sobject.Case.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CaseId__typeInfo)) {
            setCaseId(__typeMapper.readString(__in, CaseId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsSharedByEmail__typeInfo)) {
            setIsSharedByEmail((java.lang.Boolean)__typeMapper.readObject(__in, IsSharedByEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, KnowledgeArticle__typeInfo)) {
            setKnowledgeArticle((com.sforce.soap.enterprise.sobject.FAQ__ka)__typeMapper.readObject(__in, KnowledgeArticle__typeInfo, com.sforce.soap.enterprise.sobject.FAQ__ka.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, KnowledgeArticleId__typeInfo)) {
            setKnowledgeArticleId(__typeMapper.readString(__in, KnowledgeArticleId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CaseArticle ");
      sb.append(super.toString());sb.append(" ArticleLanguage=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ArticleLanguage)+"'\n");
      sb.append(" ArticleVersionNumber=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ArticleVersionNumber)+"'\n");
      sb.append(" Case=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Case)+"'\n");
      sb.append(" CaseId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CaseId)+"'\n");
      sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" IsDeleted=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsDeleted)+"'\n");
      sb.append(" IsSharedByEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsSharedByEmail)+"'\n");
      sb.append(" KnowledgeArticle=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(KnowledgeArticle)+"'\n");
      sb.append(" KnowledgeArticleId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(KnowledgeArticleId)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
