package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class Entitlement extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public Entitlement() {}

    /**
     * element : Account of type {urn:sobject.enterprise.soap.sforce.com}Account
     * java type: com.sforce.soap.enterprise.sobject.Account
     */
    private static final com.sforce.ws.bind.TypeInfo Account__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true);

    private boolean Account__is_set = false;

    private com.sforce.soap.enterprise.sobject.Account Account;

    public com.sforce.soap.enterprise.sobject.Account getAccount() {
      return Account;
    }

    public void setAccount(com.sforce.soap.enterprise.sobject.Account Account) {
      this.Account = Account;
      Account__is_set = true;
    }

    /**
     * element : AccountId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo AccountId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean AccountId__is_set = false;

    private java.lang.String AccountId;

    public java.lang.String getAccountId() {
      return AccountId;
    }

    public void setAccountId(java.lang.String AccountId) {
      this.AccountId = AccountId;
      AccountId__is_set = true;
    }

    /**
     * element : ActivityHistories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ActivityHistories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivityHistories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ActivityHistories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ActivityHistories;

    public com.sforce.soap.enterprise.QueryResult getActivityHistories() {
      return ActivityHistories;
    }

    public void setActivityHistories(com.sforce.soap.enterprise.QueryResult ActivityHistories) {
      this.ActivityHistories = ActivityHistories;
      ActivityHistories__is_set = true;
    }

    /**
     * element : Asset of type {urn:sobject.enterprise.soap.sforce.com}Asset
     * java type: com.sforce.soap.enterprise.sobject.Asset
     */
    private static final com.sforce.ws.bind.TypeInfo Asset__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Asset","urn:sobject.enterprise.soap.sforce.com","Asset",0,1,true);

    private boolean Asset__is_set = false;

    private com.sforce.soap.enterprise.sobject.Asset Asset;

    public com.sforce.soap.enterprise.sobject.Asset getAsset() {
      return Asset;
    }

    public void setAsset(com.sforce.soap.enterprise.sobject.Asset Asset) {
      this.Asset = Asset;
      Asset__is_set = true;
    }

    /**
     * element : AssetId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo AssetId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AssetId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean AssetId__is_set = false;

    private java.lang.String AssetId;

    public java.lang.String getAssetId() {
      return AssetId;
    }

    public void setAssetId(java.lang.String AssetId) {
      this.AssetId = AssetId;
      AssetId__is_set = true;
    }

    /**
     * element : AttachedContentDocuments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo AttachedContentDocuments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AttachedContentDocuments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean AttachedContentDocuments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult AttachedContentDocuments;

    public com.sforce.soap.enterprise.QueryResult getAttachedContentDocuments() {
      return AttachedContentDocuments;
    }

    public void setAttachedContentDocuments(com.sforce.soap.enterprise.QueryResult AttachedContentDocuments) {
      this.AttachedContentDocuments = AttachedContentDocuments;
      AttachedContentDocuments__is_set = true;
    }

    /**
     * element : Attachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Attachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Attachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Attachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Attachments;

    public com.sforce.soap.enterprise.QueryResult getAttachments() {
      return Attachments;
    }

    public void setAttachments(com.sforce.soap.enterprise.QueryResult Attachments) {
      this.Attachments = Attachments;
      Attachments__is_set = true;
    }

    /**
     * element : BusinessHours of type {urn:sobject.enterprise.soap.sforce.com}BusinessHours
     * java type: com.sforce.soap.enterprise.sobject.BusinessHours
     */
    private static final com.sforce.ws.bind.TypeInfo BusinessHours__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BusinessHours","urn:sobject.enterprise.soap.sforce.com","BusinessHours",0,1,true);

    private boolean BusinessHours__is_set = false;

    private com.sforce.soap.enterprise.sobject.BusinessHours BusinessHours;

    public com.sforce.soap.enterprise.sobject.BusinessHours getBusinessHours() {
      return BusinessHours;
    }

    public void setBusinessHours(com.sforce.soap.enterprise.sobject.BusinessHours BusinessHours) {
      this.BusinessHours = BusinessHours;
      BusinessHours__is_set = true;
    }

    /**
     * element : BusinessHoursId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BusinessHoursId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BusinessHoursId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean BusinessHoursId__is_set = false;

    private java.lang.String BusinessHoursId;

    public java.lang.String getBusinessHoursId() {
      return BusinessHoursId;
    }

    public void setBusinessHoursId(java.lang.String BusinessHoursId) {
      this.BusinessHoursId = BusinessHoursId;
      BusinessHoursId__is_set = true;
    }

    /**
     * element : Cases of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Cases__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Cases","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Cases__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Cases;

    public com.sforce.soap.enterprise.QueryResult getCases() {
      return Cases;
    }

    public void setCases(com.sforce.soap.enterprise.QueryResult Cases) {
      this.Cases = Cases;
      Cases__is_set = true;
    }

    /**
     * element : CasesPerEntitlement of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo CasesPerEntitlement__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CasesPerEntitlement","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean CasesPerEntitlement__is_set = false;

    private java.lang.Integer CasesPerEntitlement;

    public java.lang.Integer getCasesPerEntitlement() {
      return CasesPerEntitlement;
    }

    public void setCasesPerEntitlement(java.lang.Integer CasesPerEntitlement) {
      this.CasesPerEntitlement = CasesPerEntitlement;
      CasesPerEntitlement__is_set = true;
    }

    /**
     * element : CombinedAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo CombinedAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CombinedAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean CombinedAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult CombinedAttachments;

    public com.sforce.soap.enterprise.QueryResult getCombinedAttachments() {
      return CombinedAttachments;
    }

    public void setCombinedAttachments(com.sforce.soap.enterprise.QueryResult CombinedAttachments) {
      this.CombinedAttachments = CombinedAttachments;
      CombinedAttachments__is_set = true;
    }

    /**
     * element : ContractLineItem of type {urn:sobject.enterprise.soap.sforce.com}ContractLineItem
     * java type: com.sforce.soap.enterprise.sobject.ContractLineItem
     */
    private static final com.sforce.ws.bind.TypeInfo ContractLineItem__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContractLineItem","urn:sobject.enterprise.soap.sforce.com","ContractLineItem",0,1,true);

    private boolean ContractLineItem__is_set = false;

    private com.sforce.soap.enterprise.sobject.ContractLineItem ContractLineItem;

    public com.sforce.soap.enterprise.sobject.ContractLineItem getContractLineItem() {
      return ContractLineItem;
    }

    public void setContractLineItem(com.sforce.soap.enterprise.sobject.ContractLineItem ContractLineItem) {
      this.ContractLineItem = ContractLineItem;
      ContractLineItem__is_set = true;
    }

    /**
     * element : ContractLineItemId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ContractLineItemId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContractLineItemId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ContractLineItemId__is_set = false;

    private java.lang.String ContractLineItemId;

    public java.lang.String getContractLineItemId() {
      return ContractLineItemId;
    }

    public void setContractLineItemId(java.lang.String ContractLineItemId) {
      this.ContractLineItemId = ContractLineItemId;
      ContractLineItemId__is_set = true;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : EndDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo EndDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EndDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean EndDate__is_set = false;

    private java.util.Calendar EndDate;

    public java.util.Calendar getEndDate() {
      return EndDate;
    }

    public void setEndDate(java.util.Calendar EndDate) {
      this.EndDate = EndDate;
      EndDate__is_set = true;
    }

    /**
     * element : EntitlementContacts of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo EntitlementContacts__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EntitlementContacts","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean EntitlementContacts__is_set = false;

    private com.sforce.soap.enterprise.QueryResult EntitlementContacts;

    public com.sforce.soap.enterprise.QueryResult getEntitlementContacts() {
      return EntitlementContacts;
    }

    public void setEntitlementContacts(com.sforce.soap.enterprise.QueryResult EntitlementContacts) {
      this.EntitlementContacts = EntitlementContacts;
      EntitlementContacts__is_set = true;
    }

    /**
     * element : Events of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Events__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Events","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Events__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Events;

    public com.sforce.soap.enterprise.QueryResult getEvents() {
      return Events;
    }

    public void setEvents(com.sforce.soap.enterprise.QueryResult Events) {
      this.Events = Events;
      Events__is_set = true;
    }

    /**
     * element : FeedSubscriptionsForEntity of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo FeedSubscriptionsForEntity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FeedSubscriptionsForEntity","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean FeedSubscriptionsForEntity__is_set = false;

    private com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity;

    public com.sforce.soap.enterprise.QueryResult getFeedSubscriptionsForEntity() {
      return FeedSubscriptionsForEntity;
    }

    public void setFeedSubscriptionsForEntity(com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity) {
      this.FeedSubscriptionsForEntity = FeedSubscriptionsForEntity;
      FeedSubscriptionsForEntity__is_set = true;
    }

    /**
     * element : Feeds of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Feeds__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Feeds","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Feeds__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Feeds;

    public com.sforce.soap.enterprise.QueryResult getFeeds() {
      return Feeds;
    }

    public void setFeeds(com.sforce.soap.enterprise.QueryResult Feeds) {
      this.Feeds = Feeds;
      Feeds__is_set = true;
    }

    /**
     * element : Histories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Histories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Histories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Histories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Histories;

    public com.sforce.soap.enterprise.QueryResult getHistories() {
      return Histories;
    }

    public void setHistories(com.sforce.soap.enterprise.QueryResult Histories) {
      this.Histories = Histories;
      Histories__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : IsPerIncident of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsPerIncident__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsPerIncident","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsPerIncident__is_set = false;

    private java.lang.Boolean IsPerIncident;

    public java.lang.Boolean getIsPerIncident() {
      return IsPerIncident;
    }

    public void setIsPerIncident(java.lang.Boolean IsPerIncident) {
      this.IsPerIncident = IsPerIncident;
      IsPerIncident__is_set = true;
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    /**
     * element : LastReferencedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastReferencedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastReferencedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastReferencedDate__is_set = false;

    private java.util.Calendar LastReferencedDate;

    public java.util.Calendar getLastReferencedDate() {
      return LastReferencedDate;
    }

    public void setLastReferencedDate(java.util.Calendar LastReferencedDate) {
      this.LastReferencedDate = LastReferencedDate;
      LastReferencedDate__is_set = true;
    }

    /**
     * element : LastViewedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastViewedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastViewedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastViewedDate__is_set = false;

    private java.util.Calendar LastViewedDate;

    public java.util.Calendar getLastViewedDate() {
      return LastViewedDate;
    }

    public void setLastViewedDate(java.util.Calendar LastViewedDate) {
      this.LastViewedDate = LastViewedDate;
      LastViewedDate__is_set = true;
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    /**
     * element : Notes of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Notes__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Notes","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Notes__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Notes;

    public com.sforce.soap.enterprise.QueryResult getNotes() {
      return Notes;
    }

    public void setNotes(com.sforce.soap.enterprise.QueryResult Notes) {
      this.Notes = Notes;
      Notes__is_set = true;
    }

    /**
     * element : NotesAndAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo NotesAndAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NotesAndAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean NotesAndAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult NotesAndAttachments;

    public com.sforce.soap.enterprise.QueryResult getNotesAndAttachments() {
      return NotesAndAttachments;
    }

    public void setNotesAndAttachments(com.sforce.soap.enterprise.QueryResult NotesAndAttachments) {
      this.NotesAndAttachments = NotesAndAttachments;
      NotesAndAttachments__is_set = true;
    }

    /**
     * element : OpenActivities of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo OpenActivities__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OpenActivities","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean OpenActivities__is_set = false;

    private com.sforce.soap.enterprise.QueryResult OpenActivities;

    public com.sforce.soap.enterprise.QueryResult getOpenActivities() {
      return OpenActivities;
    }

    public void setOpenActivities(com.sforce.soap.enterprise.QueryResult OpenActivities) {
      this.OpenActivities = OpenActivities;
      OpenActivities__is_set = true;
    }

    /**
     * element : ProcessInstances of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessInstances__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessInstances","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessInstances__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessInstances;

    public com.sforce.soap.enterprise.QueryResult getProcessInstances() {
      return ProcessInstances;
    }

    public void setProcessInstances(com.sforce.soap.enterprise.QueryResult ProcessInstances) {
      this.ProcessInstances = ProcessInstances;
      ProcessInstances__is_set = true;
    }

    /**
     * element : ProcessSteps of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessSteps__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessSteps","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessSteps__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessSteps;

    public com.sforce.soap.enterprise.QueryResult getProcessSteps() {
      return ProcessSteps;
    }

    public void setProcessSteps(com.sforce.soap.enterprise.QueryResult ProcessSteps) {
      this.ProcessSteps = ProcessSteps;
      ProcessSteps__is_set = true;
    }

    /**
     * element : RemainingCases of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo RemainingCases__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","RemainingCases","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean RemainingCases__is_set = false;

    private java.lang.Integer RemainingCases;

    public java.lang.Integer getRemainingCases() {
      return RemainingCases;
    }

    public void setRemainingCases(java.lang.Integer RemainingCases) {
      this.RemainingCases = RemainingCases;
      RemainingCases__is_set = true;
    }

    /**
     * element : ServiceContract of type {urn:sobject.enterprise.soap.sforce.com}ServiceContract
     * java type: com.sforce.soap.enterprise.sobject.ServiceContract
     */
    private static final com.sforce.ws.bind.TypeInfo ServiceContract__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ServiceContract","urn:sobject.enterprise.soap.sforce.com","ServiceContract",0,1,true);

    private boolean ServiceContract__is_set = false;

    private com.sforce.soap.enterprise.sobject.ServiceContract ServiceContract;

    public com.sforce.soap.enterprise.sobject.ServiceContract getServiceContract() {
      return ServiceContract;
    }

    public void setServiceContract(com.sforce.soap.enterprise.sobject.ServiceContract ServiceContract) {
      this.ServiceContract = ServiceContract;
      ServiceContract__is_set = true;
    }

    /**
     * element : ServiceContractId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ServiceContractId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ServiceContractId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ServiceContractId__is_set = false;

    private java.lang.String ServiceContractId;

    public java.lang.String getServiceContractId() {
      return ServiceContractId;
    }

    public void setServiceContractId(java.lang.String ServiceContractId) {
      this.ServiceContractId = ServiceContractId;
      ServiceContractId__is_set = true;
    }

    /**
     * element : SlaProcess of type {urn:sobject.enterprise.soap.sforce.com}SlaProcess
     * java type: com.sforce.soap.enterprise.sobject.SlaProcess
     */
    private static final com.sforce.ws.bind.TypeInfo SlaProcess__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SlaProcess","urn:sobject.enterprise.soap.sforce.com","SlaProcess",0,1,true);

    private boolean SlaProcess__is_set = false;

    private com.sforce.soap.enterprise.sobject.SlaProcess SlaProcess;

    public com.sforce.soap.enterprise.sobject.SlaProcess getSlaProcess() {
      return SlaProcess;
    }

    public void setSlaProcess(com.sforce.soap.enterprise.sobject.SlaProcess SlaProcess) {
      this.SlaProcess = SlaProcess;
      SlaProcess__is_set = true;
    }

    /**
     * element : SlaProcessId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo SlaProcessId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SlaProcessId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean SlaProcessId__is_set = false;

    private java.lang.String SlaProcessId;

    public java.lang.String getSlaProcessId() {
      return SlaProcessId;
    }

    public void setSlaProcessId(java.lang.String SlaProcessId) {
      this.SlaProcessId = SlaProcessId;
      SlaProcessId__is_set = true;
    }

    /**
     * element : StartDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo StartDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","StartDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean StartDate__is_set = false;

    private java.util.Calendar StartDate;

    public java.util.Calendar getStartDate() {
      return StartDate;
    }

    public void setStartDate(java.util.Calendar StartDate) {
      this.StartDate = StartDate;
      StartDate__is_set = true;
    }

    /**
     * element : Status of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Status__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Status__is_set = false;

    private java.lang.String Status;

    public java.lang.String getStatus() {
      return Status;
    }

    public void setStatus(java.lang.String Status) {
      this.Status = Status;
      Status__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     * element : Tasks of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Tasks__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Tasks","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Tasks__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Tasks;

    public com.sforce.soap.enterprise.QueryResult getTasks() {
      return Tasks;
    }

    public void setTasks(com.sforce.soap.enterprise.QueryResult Tasks) {
      this.Tasks = Tasks;
      Tasks__is_set = true;
    }

    /**
     * element : Type of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Type__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Type","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Type__is_set = false;

    private java.lang.String Type;

    public java.lang.String getType() {
      return Type;
    }

    public void setType(java.lang.String Type) {
      this.Type = Type;
      Type__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "Entitlement");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, Account__typeInfo, Account, Account__is_set);
       __typeMapper.writeString(__out, AccountId__typeInfo, AccountId, AccountId__is_set);
       __typeMapper.writeObject(__out, ActivityHistories__typeInfo, ActivityHistories, ActivityHistories__is_set);
       __typeMapper.writeObject(__out, Asset__typeInfo, Asset, Asset__is_set);
       __typeMapper.writeString(__out, AssetId__typeInfo, AssetId, AssetId__is_set);
       __typeMapper.writeObject(__out, AttachedContentDocuments__typeInfo, AttachedContentDocuments, AttachedContentDocuments__is_set);
       __typeMapper.writeObject(__out, Attachments__typeInfo, Attachments, Attachments__is_set);
       __typeMapper.writeObject(__out, BusinessHours__typeInfo, BusinessHours, BusinessHours__is_set);
       __typeMapper.writeString(__out, BusinessHoursId__typeInfo, BusinessHoursId, BusinessHoursId__is_set);
       __typeMapper.writeObject(__out, Cases__typeInfo, Cases, Cases__is_set);
       __typeMapper.writeObject(__out, CasesPerEntitlement__typeInfo, CasesPerEntitlement, CasesPerEntitlement__is_set);
       __typeMapper.writeObject(__out, CombinedAttachments__typeInfo, CombinedAttachments, CombinedAttachments__is_set);
       __typeMapper.writeObject(__out, ContractLineItem__typeInfo, ContractLineItem, ContractLineItem__is_set);
       __typeMapper.writeString(__out, ContractLineItemId__typeInfo, ContractLineItemId, ContractLineItemId__is_set);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeObject(__out, EndDate__typeInfo, EndDate, EndDate__is_set);
       __typeMapper.writeObject(__out, EntitlementContacts__typeInfo, EntitlementContacts, EntitlementContacts__is_set);
       __typeMapper.writeObject(__out, Events__typeInfo, Events, Events__is_set);
       __typeMapper.writeObject(__out, FeedSubscriptionsForEntity__typeInfo, FeedSubscriptionsForEntity, FeedSubscriptionsForEntity__is_set);
       __typeMapper.writeObject(__out, Feeds__typeInfo, Feeds, Feeds__is_set);
       __typeMapper.writeObject(__out, Histories__typeInfo, Histories, Histories__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeObject(__out, IsPerIncident__typeInfo, IsPerIncident, IsPerIncident__is_set);
       __typeMapper.writeObject(__out, LastModifiedBy__typeInfo, LastModifiedBy, LastModifiedBy__is_set);
       __typeMapper.writeString(__out, LastModifiedById__typeInfo, LastModifiedById, LastModifiedById__is_set);
       __typeMapper.writeObject(__out, LastModifiedDate__typeInfo, LastModifiedDate, LastModifiedDate__is_set);
       __typeMapper.writeObject(__out, LastReferencedDate__typeInfo, LastReferencedDate, LastReferencedDate__is_set);
       __typeMapper.writeObject(__out, LastViewedDate__typeInfo, LastViewedDate, LastViewedDate__is_set);
       __typeMapper.writeString(__out, Name__typeInfo, Name, Name__is_set);
       __typeMapper.writeObject(__out, Notes__typeInfo, Notes, Notes__is_set);
       __typeMapper.writeObject(__out, NotesAndAttachments__typeInfo, NotesAndAttachments, NotesAndAttachments__is_set);
       __typeMapper.writeObject(__out, OpenActivities__typeInfo, OpenActivities, OpenActivities__is_set);
       __typeMapper.writeObject(__out, ProcessInstances__typeInfo, ProcessInstances, ProcessInstances__is_set);
       __typeMapper.writeObject(__out, ProcessSteps__typeInfo, ProcessSteps, ProcessSteps__is_set);
       __typeMapper.writeObject(__out, RemainingCases__typeInfo, RemainingCases, RemainingCases__is_set);
       __typeMapper.writeObject(__out, ServiceContract__typeInfo, ServiceContract, ServiceContract__is_set);
       __typeMapper.writeString(__out, ServiceContractId__typeInfo, ServiceContractId, ServiceContractId__is_set);
       __typeMapper.writeObject(__out, SlaProcess__typeInfo, SlaProcess, SlaProcess__is_set);
       __typeMapper.writeString(__out, SlaProcessId__typeInfo, SlaProcessId, SlaProcessId__is_set);
       __typeMapper.writeObject(__out, StartDate__typeInfo, StartDate, StartDate__is_set);
       __typeMapper.writeString(__out, Status__typeInfo, Status, Status__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
       __typeMapper.writeObject(__out, Tasks__typeInfo, Tasks, Tasks__is_set);
       __typeMapper.writeString(__out, Type__typeInfo, Type, Type__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, Account__typeInfo)) {
            setAccount((com.sforce.soap.enterprise.sobject.Account)__typeMapper.readObject(__in, Account__typeInfo, com.sforce.soap.enterprise.sobject.Account.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AccountId__typeInfo)) {
            setAccountId(__typeMapper.readString(__in, AccountId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivityHistories__typeInfo)) {
            setActivityHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ActivityHistories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Asset__typeInfo)) {
            setAsset((com.sforce.soap.enterprise.sobject.Asset)__typeMapper.readObject(__in, Asset__typeInfo, com.sforce.soap.enterprise.sobject.Asset.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AssetId__typeInfo)) {
            setAssetId(__typeMapper.readString(__in, AssetId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AttachedContentDocuments__typeInfo)) {
            setAttachedContentDocuments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, AttachedContentDocuments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Attachments__typeInfo)) {
            setAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Attachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BusinessHours__typeInfo)) {
            setBusinessHours((com.sforce.soap.enterprise.sobject.BusinessHours)__typeMapper.readObject(__in, BusinessHours__typeInfo, com.sforce.soap.enterprise.sobject.BusinessHours.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BusinessHoursId__typeInfo)) {
            setBusinessHoursId(__typeMapper.readString(__in, BusinessHoursId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Cases__typeInfo)) {
            setCases((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Cases__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CasesPerEntitlement__typeInfo)) {
            setCasesPerEntitlement((java.lang.Integer)__typeMapper.readObject(__in, CasesPerEntitlement__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CombinedAttachments__typeInfo)) {
            setCombinedAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, CombinedAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContractLineItem__typeInfo)) {
            setContractLineItem((com.sforce.soap.enterprise.sobject.ContractLineItem)__typeMapper.readObject(__in, ContractLineItem__typeInfo, com.sforce.soap.enterprise.sobject.ContractLineItem.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContractLineItemId__typeInfo)) {
            setContractLineItemId(__typeMapper.readString(__in, ContractLineItemId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EndDate__typeInfo)) {
            setEndDate((java.util.Calendar)__typeMapper.readObject(__in, EndDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EntitlementContacts__typeInfo)) {
            setEntitlementContacts((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, EntitlementContacts__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Events__typeInfo)) {
            setEvents((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Events__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FeedSubscriptionsForEntity__typeInfo)) {
            setFeedSubscriptionsForEntity((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, FeedSubscriptionsForEntity__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Feeds__typeInfo)) {
            setFeeds((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Feeds__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Histories__typeInfo)) {
            setHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Histories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsPerIncident__typeInfo)) {
            setIsPerIncident((java.lang.Boolean)__typeMapper.readObject(__in, IsPerIncident__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedBy__typeInfo)) {
            setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, LastModifiedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedById__typeInfo)) {
            setLastModifiedById(__typeMapper.readString(__in, LastModifiedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedDate__typeInfo)) {
            setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, LastModifiedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastReferencedDate__typeInfo)) {
            setLastReferencedDate((java.util.Calendar)__typeMapper.readObject(__in, LastReferencedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastViewedDate__typeInfo)) {
            setLastViewedDate((java.util.Calendar)__typeMapper.readObject(__in, LastViewedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Name__typeInfo)) {
            setName(__typeMapper.readString(__in, Name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Notes__typeInfo)) {
            setNotes((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Notes__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NotesAndAttachments__typeInfo)) {
            setNotesAndAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, NotesAndAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OpenActivities__typeInfo)) {
            setOpenActivities((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, OpenActivities__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessInstances__typeInfo)) {
            setProcessInstances((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessInstances__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessSteps__typeInfo)) {
            setProcessSteps((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessSteps__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, RemainingCases__typeInfo)) {
            setRemainingCases((java.lang.Integer)__typeMapper.readObject(__in, RemainingCases__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ServiceContract__typeInfo)) {
            setServiceContract((com.sforce.soap.enterprise.sobject.ServiceContract)__typeMapper.readObject(__in, ServiceContract__typeInfo, com.sforce.soap.enterprise.sobject.ServiceContract.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ServiceContractId__typeInfo)) {
            setServiceContractId(__typeMapper.readString(__in, ServiceContractId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SlaProcess__typeInfo)) {
            setSlaProcess((com.sforce.soap.enterprise.sobject.SlaProcess)__typeMapper.readObject(__in, SlaProcess__typeInfo, com.sforce.soap.enterprise.sobject.SlaProcess.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SlaProcessId__typeInfo)) {
            setSlaProcessId(__typeMapper.readString(__in, SlaProcessId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, StartDate__typeInfo)) {
            setStartDate((java.util.Calendar)__typeMapper.readObject(__in, StartDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Status__typeInfo)) {
            setStatus(__typeMapper.readString(__in, Status__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Tasks__typeInfo)) {
            setTasks((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Tasks__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Type__typeInfo)) {
            setType(__typeMapper.readString(__in, Type__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Entitlement ");
      sb.append(super.toString());sb.append(" Account=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Account)+"'\n");
      sb.append(" AccountId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AccountId)+"'\n");
      sb.append(" ActivityHistories=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ActivityHistories)+"'\n");
      sb.append(" Asset=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Asset)+"'\n");
      sb.append(" AssetId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AssetId)+"'\n");
      sb.append(" AttachedContentDocuments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AttachedContentDocuments)+"'\n");
      sb.append(" Attachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Attachments)+"'\n");
      sb.append(" BusinessHours=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BusinessHours)+"'\n");
      sb.append(" BusinessHoursId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BusinessHoursId)+"'\n");
      sb.append(" Cases=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Cases)+"'\n");
      sb.append(" CasesPerEntitlement=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CasesPerEntitlement)+"'\n");
      sb.append(" CombinedAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CombinedAttachments)+"'\n");
      sb.append(" ContractLineItem=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ContractLineItem)+"'\n");
      sb.append(" ContractLineItemId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ContractLineItemId)+"'\n");
      sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" EndDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(EndDate)+"'\n");
      sb.append(" EntitlementContacts=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(EntitlementContacts)+"'\n");
      sb.append(" Events=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Events)+"'\n");
      sb.append(" FeedSubscriptionsForEntity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(FeedSubscriptionsForEntity)+"'\n");
      sb.append(" Feeds=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Feeds)+"'\n");
      sb.append(" Histories=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Histories)+"'\n");
      sb.append(" IsDeleted=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsDeleted)+"'\n");
      sb.append(" IsPerIncident=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsPerIncident)+"'\n");
      sb.append(" LastModifiedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedBy)+"'\n");
      sb.append(" LastModifiedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedById)+"'\n");
      sb.append(" LastModifiedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedDate)+"'\n");
      sb.append(" LastReferencedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastReferencedDate)+"'\n");
      sb.append(" LastViewedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastViewedDate)+"'\n");
      sb.append(" Name=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Name)+"'\n");
      sb.append(" Notes=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Notes)+"'\n");
      sb.append(" NotesAndAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NotesAndAttachments)+"'\n");
      sb.append(" OpenActivities=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OpenActivities)+"'\n");
      sb.append(" ProcessInstances=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessInstances)+"'\n");
      sb.append(" ProcessSteps=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessSteps)+"'\n");
      sb.append(" RemainingCases=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(RemainingCases)+"'\n");
      sb.append(" ServiceContract=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ServiceContract)+"'\n");
      sb.append(" ServiceContractId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ServiceContractId)+"'\n");
      sb.append(" SlaProcess=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SlaProcess)+"'\n");
      sb.append(" SlaProcessId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SlaProcessId)+"'\n");
      sb.append(" StartDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(StartDate)+"'\n");
      sb.append(" Status=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Status)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append(" Tasks=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Tasks)+"'\n");
      sb.append(" Type=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Type)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
