package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class ForecastingItem extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public ForecastingItem() {}

    /**
     * element : AmountWithoutAdjustments of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo AmountWithoutAdjustments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AmountWithoutAdjustments","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean AmountWithoutAdjustments__is_set = false;

    private java.lang.Double AmountWithoutAdjustments;

    public java.lang.Double getAmountWithoutAdjustments() {
      return AmountWithoutAdjustments;
    }

    public void setAmountWithoutAdjustments(java.lang.Double AmountWithoutAdjustments) {
      this.AmountWithoutAdjustments = AmountWithoutAdjustments;
      AmountWithoutAdjustments__is_set = true;
    }

    /**
     * element : AmountWithoutManagerAdjustment of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo AmountWithoutManagerAdjustment__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AmountWithoutManagerAdjustment","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean AmountWithoutManagerAdjustment__is_set = false;

    private java.lang.Double AmountWithoutManagerAdjustment;

    public java.lang.Double getAmountWithoutManagerAdjustment() {
      return AmountWithoutManagerAdjustment;
    }

    public void setAmountWithoutManagerAdjustment(java.lang.Double AmountWithoutManagerAdjustment) {
      this.AmountWithoutManagerAdjustment = AmountWithoutManagerAdjustment;
      AmountWithoutManagerAdjustment__is_set = true;
    }

    /**
     * element : ForecastAmount of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ForecastAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ForecastAmount","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ForecastAmount__is_set = false;

    private java.lang.Double ForecastAmount;

    public java.lang.Double getForecastAmount() {
      return ForecastAmount;
    }

    public void setForecastAmount(java.lang.Double ForecastAmount) {
      this.ForecastAmount = ForecastAmount;
      ForecastAmount__is_set = true;
    }

    /**
     * element : ForecastCategoryName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ForecastCategoryName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ForecastCategoryName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ForecastCategoryName__is_set = false;

    private java.lang.String ForecastCategoryName;

    public java.lang.String getForecastCategoryName() {
      return ForecastCategoryName;
    }

    public void setForecastCategoryName(java.lang.String ForecastCategoryName) {
      this.ForecastCategoryName = ForecastCategoryName;
      ForecastCategoryName__is_set = true;
    }

    /**
     * element : ForecastQuantity of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ForecastQuantity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ForecastQuantity","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ForecastQuantity__is_set = false;

    private java.lang.Double ForecastQuantity;

    public java.lang.Double getForecastQuantity() {
      return ForecastQuantity;
    }

    public void setForecastQuantity(java.lang.Double ForecastQuantity) {
      this.ForecastQuantity = ForecastQuantity;
      ForecastQuantity__is_set = true;
    }

    /**
     * element : HasAdjustment of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo HasAdjustment__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","HasAdjustment","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean HasAdjustment__is_set = false;

    private java.lang.Boolean HasAdjustment;

    public java.lang.Boolean getHasAdjustment() {
      return HasAdjustment;
    }

    public void setHasAdjustment(java.lang.Boolean HasAdjustment) {
      this.HasAdjustment = HasAdjustment;
      HasAdjustment__is_set = true;
    }

    /**
     * element : IsAmount of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsAmount","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsAmount__is_set = false;

    private java.lang.Boolean IsAmount;

    public java.lang.Boolean getIsAmount() {
      return IsAmount;
    }

    public void setIsAmount(java.lang.Boolean IsAmount) {
      this.IsAmount = IsAmount;
      IsAmount__is_set = true;
    }

    /**
     * element : IsQuantity of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsQuantity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsQuantity","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsQuantity__is_set = false;

    private java.lang.Boolean IsQuantity;

    public java.lang.Boolean getIsQuantity() {
      return IsQuantity;
    }

    public void setIsQuantity(java.lang.Boolean IsQuantity) {
      this.IsQuantity = IsQuantity;
      IsQuantity__is_set = true;
    }

    /**
     * element : IsUpToDate of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsUpToDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsUpToDate","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsUpToDate__is_set = false;

    private java.lang.Boolean IsUpToDate;

    public java.lang.Boolean getIsUpToDate() {
      return IsUpToDate;
    }

    public void setIsUpToDate(java.lang.Boolean IsUpToDate) {
      this.IsUpToDate = IsUpToDate;
      IsUpToDate__is_set = true;
    }

    /**
     * element : Owner of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo Owner__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Owner","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean Owner__is_set = false;

    private com.sforce.soap.enterprise.sobject.User Owner;

    public com.sforce.soap.enterprise.sobject.User getOwner() {
      return Owner;
    }

    public void setOwner(com.sforce.soap.enterprise.sobject.User Owner) {
      this.Owner = Owner;
      Owner__is_set = true;
    }

    /**
     * element : OwnerId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OwnerId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean OwnerId__is_set = false;

    private java.lang.String OwnerId;

    public java.lang.String getOwnerId() {
      return OwnerId;
    }

    public void setOwnerId(java.lang.String OwnerId) {
      this.OwnerId = OwnerId;
      OwnerId__is_set = true;
    }

    /**
     * element : OwnerOnlyAmount of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo OwnerOnlyAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OwnerOnlyAmount","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean OwnerOnlyAmount__is_set = false;

    private java.lang.Double OwnerOnlyAmount;

    public java.lang.Double getOwnerOnlyAmount() {
      return OwnerOnlyAmount;
    }

    public void setOwnerOnlyAmount(java.lang.Double OwnerOnlyAmount) {
      this.OwnerOnlyAmount = OwnerOnlyAmount;
      OwnerOnlyAmount__is_set = true;
    }

    /**
     * element : OwnerOnlyQuantity of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo OwnerOnlyQuantity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OwnerOnlyQuantity","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean OwnerOnlyQuantity__is_set = false;

    private java.lang.Double OwnerOnlyQuantity;

    public java.lang.Double getOwnerOnlyQuantity() {
      return OwnerOnlyQuantity;
    }

    public void setOwnerOnlyQuantity(java.lang.Double OwnerOnlyQuantity) {
      this.OwnerOnlyQuantity = OwnerOnlyQuantity;
      OwnerOnlyQuantity__is_set = true;
    }

    /**
     * element : ParentForecastingItem of type {urn:sobject.enterprise.soap.sforce.com}ForecastingItem
     * java type: com.sforce.soap.enterprise.sobject.ForecastingItem
     */
    private static final com.sforce.ws.bind.TypeInfo ParentForecastingItem__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ParentForecastingItem","urn:sobject.enterprise.soap.sforce.com","ForecastingItem",0,1,true);

    private boolean ParentForecastingItem__is_set = false;

    private com.sforce.soap.enterprise.sobject.ForecastingItem ParentForecastingItem;

    public com.sforce.soap.enterprise.sobject.ForecastingItem getParentForecastingItem() {
      return ParentForecastingItem;
    }

    public void setParentForecastingItem(com.sforce.soap.enterprise.sobject.ForecastingItem ParentForecastingItem) {
      this.ParentForecastingItem = ParentForecastingItem;
      ParentForecastingItem__is_set = true;
    }

    /**
     * element : ParentForecastingItemId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ParentForecastingItemId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ParentForecastingItemId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ParentForecastingItemId__is_set = false;

    private java.lang.String ParentForecastingItemId;

    public java.lang.String getParentForecastingItemId() {
      return ParentForecastingItemId;
    }

    public void setParentForecastingItemId(java.lang.String ParentForecastingItemId) {
      this.ParentForecastingItemId = ParentForecastingItemId;
      ParentForecastingItemId__is_set = true;
    }

    /**
     * element : Period of type {urn:sobject.enterprise.soap.sforce.com}Period
     * java type: com.sforce.soap.enterprise.sobject.Period
     */
    private static final com.sforce.ws.bind.TypeInfo Period__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Period","urn:sobject.enterprise.soap.sforce.com","Period",0,1,true);

    private boolean Period__is_set = false;

    private com.sforce.soap.enterprise.sobject.Period Period;

    public com.sforce.soap.enterprise.sobject.Period getPeriod() {
      return Period;
    }

    public void setPeriod(com.sforce.soap.enterprise.sobject.Period Period) {
      this.Period = Period;
      Period__is_set = true;
    }

    /**
     * element : PeriodId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo PeriodId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PeriodId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean PeriodId__is_set = false;

    private java.lang.String PeriodId;

    public java.lang.String getPeriodId() {
      return PeriodId;
    }

    public void setPeriodId(java.lang.String PeriodId) {
      this.PeriodId = PeriodId;
      PeriodId__is_set = true;
    }

    /**
     * element : ProductFamily of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ProductFamily__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProductFamily","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ProductFamily__is_set = false;

    private java.lang.String ProductFamily;

    public java.lang.String getProductFamily() {
      return ProductFamily;
    }

    public void setProductFamily(java.lang.String ProductFamily) {
      this.ProductFamily = ProductFamily;
      ProductFamily__is_set = true;
    }

    /**
     * element : QuantityWithoutAdjustments of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo QuantityWithoutAdjustments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuantityWithoutAdjustments","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean QuantityWithoutAdjustments__is_set = false;

    private java.lang.Double QuantityWithoutAdjustments;

    public java.lang.Double getQuantityWithoutAdjustments() {
      return QuantityWithoutAdjustments;
    }

    public void setQuantityWithoutAdjustments(java.lang.Double QuantityWithoutAdjustments) {
      this.QuantityWithoutAdjustments = QuantityWithoutAdjustments;
      QuantityWithoutAdjustments__is_set = true;
    }

    /**
     * element : QuantityWithoutManagerAdjustment of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo QuantityWithoutManagerAdjustment__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuantityWithoutManagerAdjustment","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean QuantityWithoutManagerAdjustment__is_set = false;

    private java.lang.Double QuantityWithoutManagerAdjustment;

    public java.lang.Double getQuantityWithoutManagerAdjustment() {
      return QuantityWithoutManagerAdjustment;
    }

    public void setQuantityWithoutManagerAdjustment(java.lang.Double QuantityWithoutManagerAdjustment) {
      this.QuantityWithoutManagerAdjustment = QuantityWithoutManagerAdjustment;
      QuantityWithoutManagerAdjustment__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "ForecastingItem");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, AmountWithoutAdjustments__typeInfo, AmountWithoutAdjustments, AmountWithoutAdjustments__is_set);
       __typeMapper.writeObject(__out, AmountWithoutManagerAdjustment__typeInfo, AmountWithoutManagerAdjustment, AmountWithoutManagerAdjustment__is_set);
       __typeMapper.writeObject(__out, ForecastAmount__typeInfo, ForecastAmount, ForecastAmount__is_set);
       __typeMapper.writeString(__out, ForecastCategoryName__typeInfo, ForecastCategoryName, ForecastCategoryName__is_set);
       __typeMapper.writeObject(__out, ForecastQuantity__typeInfo, ForecastQuantity, ForecastQuantity__is_set);
       __typeMapper.writeObject(__out, HasAdjustment__typeInfo, HasAdjustment, HasAdjustment__is_set);
       __typeMapper.writeObject(__out, IsAmount__typeInfo, IsAmount, IsAmount__is_set);
       __typeMapper.writeObject(__out, IsQuantity__typeInfo, IsQuantity, IsQuantity__is_set);
       __typeMapper.writeObject(__out, IsUpToDate__typeInfo, IsUpToDate, IsUpToDate__is_set);
       __typeMapper.writeObject(__out, Owner__typeInfo, Owner, Owner__is_set);
       __typeMapper.writeString(__out, OwnerId__typeInfo, OwnerId, OwnerId__is_set);
       __typeMapper.writeObject(__out, OwnerOnlyAmount__typeInfo, OwnerOnlyAmount, OwnerOnlyAmount__is_set);
       __typeMapper.writeObject(__out, OwnerOnlyQuantity__typeInfo, OwnerOnlyQuantity, OwnerOnlyQuantity__is_set);
       __typeMapper.writeObject(__out, ParentForecastingItem__typeInfo, ParentForecastingItem, ParentForecastingItem__is_set);
       __typeMapper.writeString(__out, ParentForecastingItemId__typeInfo, ParentForecastingItemId, ParentForecastingItemId__is_set);
       __typeMapper.writeObject(__out, Period__typeInfo, Period, Period__is_set);
       __typeMapper.writeString(__out, PeriodId__typeInfo, PeriodId, PeriodId__is_set);
       __typeMapper.writeString(__out, ProductFamily__typeInfo, ProductFamily, ProductFamily__is_set);
       __typeMapper.writeObject(__out, QuantityWithoutAdjustments__typeInfo, QuantityWithoutAdjustments, QuantityWithoutAdjustments__is_set);
       __typeMapper.writeObject(__out, QuantityWithoutManagerAdjustment__typeInfo, QuantityWithoutManagerAdjustment, QuantityWithoutManagerAdjustment__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, AmountWithoutAdjustments__typeInfo)) {
            setAmountWithoutAdjustments((java.lang.Double)__typeMapper.readObject(__in, AmountWithoutAdjustments__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AmountWithoutManagerAdjustment__typeInfo)) {
            setAmountWithoutManagerAdjustment((java.lang.Double)__typeMapper.readObject(__in, AmountWithoutManagerAdjustment__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ForecastAmount__typeInfo)) {
            setForecastAmount((java.lang.Double)__typeMapper.readObject(__in, ForecastAmount__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ForecastCategoryName__typeInfo)) {
            setForecastCategoryName(__typeMapper.readString(__in, ForecastCategoryName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ForecastQuantity__typeInfo)) {
            setForecastQuantity((java.lang.Double)__typeMapper.readObject(__in, ForecastQuantity__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, HasAdjustment__typeInfo)) {
            setHasAdjustment((java.lang.Boolean)__typeMapper.readObject(__in, HasAdjustment__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsAmount__typeInfo)) {
            setIsAmount((java.lang.Boolean)__typeMapper.readObject(__in, IsAmount__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsQuantity__typeInfo)) {
            setIsQuantity((java.lang.Boolean)__typeMapper.readObject(__in, IsQuantity__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsUpToDate__typeInfo)) {
            setIsUpToDate((java.lang.Boolean)__typeMapper.readObject(__in, IsUpToDate__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Owner__typeInfo)) {
            setOwner((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, Owner__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OwnerId__typeInfo)) {
            setOwnerId(__typeMapper.readString(__in, OwnerId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OwnerOnlyAmount__typeInfo)) {
            setOwnerOnlyAmount((java.lang.Double)__typeMapper.readObject(__in, OwnerOnlyAmount__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OwnerOnlyQuantity__typeInfo)) {
            setOwnerOnlyQuantity((java.lang.Double)__typeMapper.readObject(__in, OwnerOnlyQuantity__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ParentForecastingItem__typeInfo)) {
            setParentForecastingItem((com.sforce.soap.enterprise.sobject.ForecastingItem)__typeMapper.readObject(__in, ParentForecastingItem__typeInfo, com.sforce.soap.enterprise.sobject.ForecastingItem.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ParentForecastingItemId__typeInfo)) {
            setParentForecastingItemId(__typeMapper.readString(__in, ParentForecastingItemId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Period__typeInfo)) {
            setPeriod((com.sforce.soap.enterprise.sobject.Period)__typeMapper.readObject(__in, Period__typeInfo, com.sforce.soap.enterprise.sobject.Period.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PeriodId__typeInfo)) {
            setPeriodId(__typeMapper.readString(__in, PeriodId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProductFamily__typeInfo)) {
            setProductFamily(__typeMapper.readString(__in, ProductFamily__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuantityWithoutAdjustments__typeInfo)) {
            setQuantityWithoutAdjustments((java.lang.Double)__typeMapper.readObject(__in, QuantityWithoutAdjustments__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuantityWithoutManagerAdjustment__typeInfo)) {
            setQuantityWithoutManagerAdjustment((java.lang.Double)__typeMapper.readObject(__in, QuantityWithoutManagerAdjustment__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ForecastingItem ");
      sb.append(super.toString());sb.append(" AmountWithoutAdjustments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AmountWithoutAdjustments)+"'\n");
      sb.append(" AmountWithoutManagerAdjustment=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AmountWithoutManagerAdjustment)+"'\n");
      sb.append(" ForecastAmount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ForecastAmount)+"'\n");
      sb.append(" ForecastCategoryName=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ForecastCategoryName)+"'\n");
      sb.append(" ForecastQuantity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ForecastQuantity)+"'\n");
      sb.append(" HasAdjustment=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(HasAdjustment)+"'\n");
      sb.append(" IsAmount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsAmount)+"'\n");
      sb.append(" IsQuantity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsQuantity)+"'\n");
      sb.append(" IsUpToDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsUpToDate)+"'\n");
      sb.append(" Owner=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Owner)+"'\n");
      sb.append(" OwnerId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OwnerId)+"'\n");
      sb.append(" OwnerOnlyAmount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OwnerOnlyAmount)+"'\n");
      sb.append(" OwnerOnlyQuantity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OwnerOnlyQuantity)+"'\n");
      sb.append(" ParentForecastingItem=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ParentForecastingItem)+"'\n");
      sb.append(" ParentForecastingItemId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ParentForecastingItemId)+"'\n");
      sb.append(" Period=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Period)+"'\n");
      sb.append(" PeriodId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PeriodId)+"'\n");
      sb.append(" ProductFamily=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProductFamily)+"'\n");
      sb.append(" QuantityWithoutAdjustments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuantityWithoutAdjustments)+"'\n");
      sb.append(" QuantityWithoutManagerAdjustment=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuantityWithoutManagerAdjustment)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
