package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class ForecastingQuota extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public ForecastingQuota() {}

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : IsAmount of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsAmount","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsAmount__is_set = false;

    private java.lang.Boolean IsAmount;

    public java.lang.Boolean getIsAmount() {
      return IsAmount;
    }

    public void setIsAmount(java.lang.Boolean IsAmount) {
      this.IsAmount = IsAmount;
      IsAmount__is_set = true;
    }

    /**
     * element : IsQuantity of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsQuantity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsQuantity","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsQuantity__is_set = false;

    private java.lang.Boolean IsQuantity;

    public java.lang.Boolean getIsQuantity() {
      return IsQuantity;
    }

    public void setIsQuantity(java.lang.Boolean IsQuantity) {
      this.IsQuantity = IsQuantity;
      IsQuantity__is_set = true;
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    /**
     * element : PeriodId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo PeriodId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PeriodId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean PeriodId__is_set = false;

    private java.lang.String PeriodId;

    public java.lang.String getPeriodId() {
      return PeriodId;
    }

    public void setPeriodId(java.lang.String PeriodId) {
      this.PeriodId = PeriodId;
      PeriodId__is_set = true;
    }

    /**
     * element : ProductFamily of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ProductFamily__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProductFamily","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ProductFamily__is_set = false;

    private java.lang.String ProductFamily;

    public java.lang.String getProductFamily() {
      return ProductFamily;
    }

    public void setProductFamily(java.lang.String ProductFamily) {
      this.ProductFamily = ProductFamily;
      ProductFamily__is_set = true;
    }

    /**
     * element : QuotaAmount of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo QuotaAmount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuotaAmount","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean QuotaAmount__is_set = false;

    private java.lang.Double QuotaAmount;

    public java.lang.Double getQuotaAmount() {
      return QuotaAmount;
    }

    public void setQuotaAmount(java.lang.Double QuotaAmount) {
      this.QuotaAmount = QuotaAmount;
      QuotaAmount__is_set = true;
    }

    /**
     * element : QuotaOwner of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo QuotaOwner__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuotaOwner","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean QuotaOwner__is_set = false;

    private com.sforce.soap.enterprise.sobject.User QuotaOwner;

    public com.sforce.soap.enterprise.sobject.User getQuotaOwner() {
      return QuotaOwner;
    }

    public void setQuotaOwner(com.sforce.soap.enterprise.sobject.User QuotaOwner) {
      this.QuotaOwner = QuotaOwner;
      QuotaOwner__is_set = true;
    }

    /**
     * element : QuotaOwnerId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo QuotaOwnerId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuotaOwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean QuotaOwnerId__is_set = false;

    private java.lang.String QuotaOwnerId;

    public java.lang.String getQuotaOwnerId() {
      return QuotaOwnerId;
    }

    public void setQuotaOwnerId(java.lang.String QuotaOwnerId) {
      this.QuotaOwnerId = QuotaOwnerId;
      QuotaOwnerId__is_set = true;
    }

    /**
     * element : QuotaQuantity of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo QuotaQuantity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","QuotaQuantity","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean QuotaQuantity__is_set = false;

    private java.lang.Double QuotaQuantity;

    public java.lang.Double getQuotaQuantity() {
      return QuotaQuantity;
    }

    public void setQuotaQuantity(java.lang.Double QuotaQuantity) {
      this.QuotaQuantity = QuotaQuantity;
      QuotaQuantity__is_set = true;
    }

    /**
     * element : StartDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo StartDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","StartDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean StartDate__is_set = false;

    private java.util.Calendar StartDate;

    public java.util.Calendar getStartDate() {
      return StartDate;
    }

    public void setStartDate(java.util.Calendar StartDate) {
      this.StartDate = StartDate;
      StartDate__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "ForecastingQuota");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeObject(__out, IsAmount__typeInfo, IsAmount, IsAmount__is_set);
       __typeMapper.writeObject(__out, IsQuantity__typeInfo, IsQuantity, IsQuantity__is_set);
       __typeMapper.writeObject(__out, LastModifiedBy__typeInfo, LastModifiedBy, LastModifiedBy__is_set);
       __typeMapper.writeString(__out, LastModifiedById__typeInfo, LastModifiedById, LastModifiedById__is_set);
       __typeMapper.writeObject(__out, LastModifiedDate__typeInfo, LastModifiedDate, LastModifiedDate__is_set);
       __typeMapper.writeString(__out, PeriodId__typeInfo, PeriodId, PeriodId__is_set);
       __typeMapper.writeString(__out, ProductFamily__typeInfo, ProductFamily, ProductFamily__is_set);
       __typeMapper.writeObject(__out, QuotaAmount__typeInfo, QuotaAmount, QuotaAmount__is_set);
       __typeMapper.writeObject(__out, QuotaOwner__typeInfo, QuotaOwner, QuotaOwner__is_set);
       __typeMapper.writeString(__out, QuotaOwnerId__typeInfo, QuotaOwnerId, QuotaOwnerId__is_set);
       __typeMapper.writeObject(__out, QuotaQuantity__typeInfo, QuotaQuantity, QuotaQuantity__is_set);
       __typeMapper.writeObject(__out, StartDate__typeInfo, StartDate, StartDate__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsAmount__typeInfo)) {
            setIsAmount((java.lang.Boolean)__typeMapper.readObject(__in, IsAmount__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsQuantity__typeInfo)) {
            setIsQuantity((java.lang.Boolean)__typeMapper.readObject(__in, IsQuantity__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedBy__typeInfo)) {
            setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, LastModifiedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedById__typeInfo)) {
            setLastModifiedById(__typeMapper.readString(__in, LastModifiedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedDate__typeInfo)) {
            setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, LastModifiedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PeriodId__typeInfo)) {
            setPeriodId(__typeMapper.readString(__in, PeriodId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProductFamily__typeInfo)) {
            setProductFamily(__typeMapper.readString(__in, ProductFamily__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuotaAmount__typeInfo)) {
            setQuotaAmount((java.lang.Double)__typeMapper.readObject(__in, QuotaAmount__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuotaOwner__typeInfo)) {
            setQuotaOwner((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, QuotaOwner__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuotaOwnerId__typeInfo)) {
            setQuotaOwnerId(__typeMapper.readString(__in, QuotaOwnerId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, QuotaQuantity__typeInfo)) {
            setQuotaQuantity((java.lang.Double)__typeMapper.readObject(__in, QuotaQuantity__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, StartDate__typeInfo)) {
            setStartDate((java.util.Calendar)__typeMapper.readObject(__in, StartDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ForecastingQuota ");
      sb.append(super.toString());sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" IsAmount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsAmount)+"'\n");
      sb.append(" IsQuantity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsQuantity)+"'\n");
      sb.append(" LastModifiedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedBy)+"'\n");
      sb.append(" LastModifiedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedById)+"'\n");
      sb.append(" LastModifiedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedDate)+"'\n");
      sb.append(" PeriodId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PeriodId)+"'\n");
      sb.append(" ProductFamily=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProductFamily)+"'\n");
      sb.append(" QuotaAmount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuotaAmount)+"'\n");
      sb.append(" QuotaOwner=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuotaOwner)+"'\n");
      sb.append(" QuotaOwnerId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuotaOwnerId)+"'\n");
      sb.append(" QuotaQuantity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(QuotaQuantity)+"'\n");
      sb.append(" StartDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(StartDate)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
