package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class Hierarchy__c extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public Hierarchy__c() {}

    /**
     * element : AboutMe__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo AboutMe__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AboutMe__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean AboutMe__c__is_set = false;

    private java.lang.String AboutMe__c;

    public java.lang.String getAboutMe__c() {
      return AboutMe__c;
    }

    public void setAboutMe__c(java.lang.String AboutMe__c) {
      this.AboutMe__c = AboutMe__c;
      AboutMe__c__is_set = true;
    }

    /**
     * element : AttachedContentDocuments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo AttachedContentDocuments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AttachedContentDocuments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean AttachedContentDocuments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult AttachedContentDocuments;

    public com.sforce.soap.enterprise.QueryResult getAttachedContentDocuments() {
      return AttachedContentDocuments;
    }

    public void setAttachedContentDocuments(com.sforce.soap.enterprise.QueryResult AttachedContentDocuments) {
      this.AttachedContentDocuments = AttachedContentDocuments;
      AttachedContentDocuments__is_set = true;
    }

    /**
     * element : Attachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Attachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Attachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Attachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Attachments;

    public com.sforce.soap.enterprise.QueryResult getAttachments() {
      return Attachments;
    }

    public void setAttachments(com.sforce.soap.enterprise.QueryResult Attachments) {
      this.Attachments = Attachments;
      Attachments__is_set = true;
    }

    /**
     * element : CombinedAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo CombinedAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CombinedAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean CombinedAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult CombinedAttachments;

    public com.sforce.soap.enterprise.QueryResult getCombinedAttachments() {
      return CombinedAttachments;
    }

    public void setCombinedAttachments(com.sforce.soap.enterprise.QueryResult CombinedAttachments) {
      this.CombinedAttachments = CombinedAttachments;
      CombinedAttachments__is_set = true;
    }

    /**
     * element : Contact__c of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Contact__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Contact__c","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean Contact__c__is_set = false;

    private java.lang.String Contact__c;

    public java.lang.String getContact__c() {
      return Contact__c;
    }

    public void setContact__c(java.lang.String Contact__c) {
      this.Contact__c = Contact__c;
      Contact__c__is_set = true;
    }

    /**
     * element : Contact__r of type {urn:sobject.enterprise.soap.sforce.com}Contact
     * java type: com.sforce.soap.enterprise.sobject.Contact
     */
    private static final com.sforce.ws.bind.TypeInfo Contact__r__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Contact__r","urn:sobject.enterprise.soap.sforce.com","Contact",0,1,true);

    private boolean Contact__r__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contact Contact__r;

    public com.sforce.soap.enterprise.sobject.Contact getContact__r() {
      return Contact__r;
    }

    public void setContact__r(com.sforce.soap.enterprise.sobject.Contact Contact__r) {
      this.Contact__r = Contact__r;
      Contact__r__is_set = true;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : Delete__c of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo Delete__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Delete__c","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean Delete__c__is_set = false;

    private java.lang.Boolean Delete__c;

    public java.lang.Boolean getDelete__c() {
      return Delete__c;
    }

    public void setDelete__c(java.lang.Boolean Delete__c) {
      this.Delete__c = Delete__c;
      Delete__c__is_set = true;
    }

    /**
     * element : DependentUserName__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo DependentUserName__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DependentUserName__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean DependentUserName__c__is_set = false;

    private java.lang.String DependentUserName__c;

    public java.lang.String getDependentUserName__c() {
      return DependentUserName__c;
    }

    public void setDependentUserName__c(java.lang.String DependentUserName__c) {
      this.DependentUserName__c = DependentUserName__c;
      DependentUserName__c__is_set = true;
    }

    /**
     * element : DependentUser__c of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo DependentUser__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DependentUser__c","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean DependentUser__c__is_set = false;

    private java.lang.String DependentUser__c;

    public java.lang.String getDependentUser__c() {
      return DependentUser__c;
    }

    public void setDependentUser__c(java.lang.String DependentUser__c) {
      this.DependentUser__c = DependentUser__c;
      DependentUser__c__is_set = true;
    }

    /**
     * element : DependentUser__r of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo DependentUser__r__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DependentUser__r","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean DependentUser__r__is_set = false;

    private com.sforce.soap.enterprise.sobject.User DependentUser__r;

    public com.sforce.soap.enterprise.sobject.User getDependentUser__r() {
      return DependentUser__r;
    }

    public void setDependentUser__r(com.sforce.soap.enterprise.sobject.User DependentUser__r) {
      this.DependentUser__r = DependentUser__r;
      DependentUser__r__is_set = true;
    }

    /**
     * element : Description__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Description__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Description__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Description__c__is_set = false;

    private java.lang.String Description__c;

    public java.lang.String getDescription__c() {
      return Description__c;
    }

    public void setDescription__c(java.lang.String Description__c) {
      this.Description__c = Description__c;
      Description__c__is_set = true;
    }

    /**
     * element : Email__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Email__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Email__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Email__c__is_set = false;

    private java.lang.String Email__c;

    public java.lang.String getEmail__c() {
      return Email__c;
    }

    public void setEmail__c(java.lang.String Email__c) {
      this.Email__c = Email__c;
      Email__c__is_set = true;
    }

    /**
     * element : FeedSubscriptionsForEntity of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo FeedSubscriptionsForEntity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FeedSubscriptionsForEntity","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean FeedSubscriptionsForEntity__is_set = false;

    private com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity;

    public com.sforce.soap.enterprise.QueryResult getFeedSubscriptionsForEntity() {
      return FeedSubscriptionsForEntity;
    }

    public void setFeedSubscriptionsForEntity(com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity) {
      this.FeedSubscriptionsForEntity = FeedSubscriptionsForEntity;
      FeedSubscriptionsForEntity__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    /**
     * element : LastReferencedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastReferencedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastReferencedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastReferencedDate__is_set = false;

    private java.util.Calendar LastReferencedDate;

    public java.util.Calendar getLastReferencedDate() {
      return LastReferencedDate;
    }

    public void setLastReferencedDate(java.util.Calendar LastReferencedDate) {
      this.LastReferencedDate = LastReferencedDate;
      LastReferencedDate__is_set = true;
    }

    /**
     * element : LastViewedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastViewedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastViewedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastViewedDate__is_set = false;

    private java.util.Calendar LastViewedDate;

    public java.util.Calendar getLastViewedDate() {
      return LastViewedDate;
    }

    public void setLastViewedDate(java.util.Calendar LastViewedDate) {
      this.LastViewedDate = LastViewedDate;
      LastViewedDate__is_set = true;
    }

    /**
     * element : MobilePhone__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo MobilePhone__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","MobilePhone__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean MobilePhone__c__is_set = false;

    private java.lang.String MobilePhone__c;

    public java.lang.String getMobilePhone__c() {
      return MobilePhone__c;
    }

    public void setMobilePhone__c(java.lang.String MobilePhone__c) {
      this.MobilePhone__c = MobilePhone__c;
      MobilePhone__c__is_set = true;
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    /**
     * element : NameUser__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo NameUser__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NameUser__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean NameUser__c__is_set = false;

    private java.lang.String NameUser__c;

    public java.lang.String getNameUser__c() {
      return NameUser__c;
    }

    public void setNameUser__c(java.lang.String NameUser__c) {
      this.NameUser__c = NameUser__c;
      NameUser__c__is_set = true;
    }

    /**
     * element : Nivel_de_escalado__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Nivel_de_escalado__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Nivel_de_escalado__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Nivel_de_escalado__c__is_set = false;

    private java.lang.String Nivel_de_escalado__c;

    public java.lang.String getNivel_de_escalado__c() {
      return Nivel_de_escalado__c;
    }

    public void setNivel_de_escalado__c(java.lang.String Nivel_de_escalado__c) {
      this.Nivel_de_escalado__c = Nivel_de_escalado__c;
      Nivel_de_escalado__c__is_set = true;
    }

    /**
     * element : Notes of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Notes__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Notes","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Notes__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Notes;

    public com.sforce.soap.enterprise.QueryResult getNotes() {
      return Notes;
    }

    public void setNotes(com.sforce.soap.enterprise.QueryResult Notes) {
      this.Notes = Notes;
      Notes__is_set = true;
    }

    /**
     * element : NotesAndAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo NotesAndAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NotesAndAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean NotesAndAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult NotesAndAttachments;

    public com.sforce.soap.enterprise.QueryResult getNotesAndAttachments() {
      return NotesAndAttachments;
    }

    public void setNotesAndAttachments(com.sforce.soap.enterprise.QueryResult NotesAndAttachments) {
      this.NotesAndAttachments = NotesAndAttachments;
      NotesAndAttachments__is_set = true;
    }

    /**
     * element : Orden__c of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo Orden__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Orden__c","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean Orden__c__is_set = false;

    private java.lang.Double Orden__c;

    public java.lang.Double getOrden__c() {
      return Orden__c;
    }

    public void setOrden__c(java.lang.Double Orden__c) {
      this.Orden__c = Orden__c;
      Orden__c__is_set = true;
    }

    /**
     * element : Phone__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Phone__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Phone__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Phone__c__is_set = false;

    private java.lang.String Phone__c;

    public java.lang.String getPhone__c() {
      return Phone__c;
    }

    public void setPhone__c(java.lang.String Phone__c) {
      this.Phone__c = Phone__c;
      Phone__c__is_set = true;
    }

    /**
     * element : Photo__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Photo__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Photo__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Photo__c__is_set = false;

    private java.lang.String Photo__c;

    public java.lang.String getPhoto__c() {
      return Photo__c;
    }

    public void setPhoto__c(java.lang.String Photo__c) {
      this.Photo__c = Photo__c;
      Photo__c__is_set = true;
    }

    /**
     * element : ProcessInstances of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessInstances__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessInstances","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessInstances__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessInstances;

    public com.sforce.soap.enterprise.QueryResult getProcessInstances() {
      return ProcessInstances;
    }

    public void setProcessInstances(com.sforce.soap.enterprise.QueryResult ProcessInstances) {
      this.ProcessInstances = ProcessInstances;
      ProcessInstances__is_set = true;
    }

    /**
     * element : ProcessSteps of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessSteps__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessSteps","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessSteps__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessSteps;

    public com.sforce.soap.enterprise.QueryResult getProcessSteps() {
      return ProcessSteps;
    }

    public void setProcessSteps(com.sforce.soap.enterprise.QueryResult ProcessSteps) {
      this.ProcessSteps = ProcessSteps;
      ProcessSteps__is_set = true;
    }

    /**
     * element : Role__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Role__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Role__c","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Role__c__is_set = false;

    private java.lang.String Role__c;

    public java.lang.String getRole__c() {
      return Role__c;
    }

    public void setRole__c(java.lang.String Role__c) {
      this.Role__c = Role__c;
      Role__c__is_set = true;
    }

    /**
     * element : ShowPersonalData__c of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo ShowPersonalData__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShowPersonalData__c","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean ShowPersonalData__c__is_set = false;

    private java.lang.Boolean ShowPersonalData__c;

    public java.lang.Boolean getShowPersonalData__c() {
      return ShowPersonalData__c;
    }

    public void setShowPersonalData__c(java.lang.Boolean ShowPersonalData__c) {
      this.ShowPersonalData__c = ShowPersonalData__c;
      ShowPersonalData__c__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     * element : User__c of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo User__c__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","User__c","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean User__c__is_set = false;

    private java.lang.String User__c;

    public java.lang.String getUser__c() {
      return User__c;
    }

    public void setUser__c(java.lang.String User__c) {
      this.User__c = User__c;
      User__c__is_set = true;
    }

    /**
     * element : User__r of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo User__r__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","User__r","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean User__r__is_set = false;

    private com.sforce.soap.enterprise.sobject.User User__r;

    public com.sforce.soap.enterprise.sobject.User getUser__r() {
      return User__r;
    }

    public void setUser__r(com.sforce.soap.enterprise.sobject.User User__r) {
      this.User__r = User__r;
      User__r__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "Hierarchy__c");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeString(__out, AboutMe__c__typeInfo, AboutMe__c, AboutMe__c__is_set);
       __typeMapper.writeObject(__out, AttachedContentDocuments__typeInfo, AttachedContentDocuments, AttachedContentDocuments__is_set);
       __typeMapper.writeObject(__out, Attachments__typeInfo, Attachments, Attachments__is_set);
       __typeMapper.writeObject(__out, CombinedAttachments__typeInfo, CombinedAttachments, CombinedAttachments__is_set);
       __typeMapper.writeString(__out, Contact__c__typeInfo, Contact__c, Contact__c__is_set);
       __typeMapper.writeObject(__out, Contact__r__typeInfo, Contact__r, Contact__r__is_set);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeObject(__out, Delete__c__typeInfo, Delete__c, Delete__c__is_set);
       __typeMapper.writeString(__out, DependentUserName__c__typeInfo, DependentUserName__c, DependentUserName__c__is_set);
       __typeMapper.writeString(__out, DependentUser__c__typeInfo, DependentUser__c, DependentUser__c__is_set);
       __typeMapper.writeObject(__out, DependentUser__r__typeInfo, DependentUser__r, DependentUser__r__is_set);
       __typeMapper.writeString(__out, Description__c__typeInfo, Description__c, Description__c__is_set);
       __typeMapper.writeString(__out, Email__c__typeInfo, Email__c, Email__c__is_set);
       __typeMapper.writeObject(__out, FeedSubscriptionsForEntity__typeInfo, FeedSubscriptionsForEntity, FeedSubscriptionsForEntity__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeObject(__out, LastModifiedBy__typeInfo, LastModifiedBy, LastModifiedBy__is_set);
       __typeMapper.writeString(__out, LastModifiedById__typeInfo, LastModifiedById, LastModifiedById__is_set);
       __typeMapper.writeObject(__out, LastModifiedDate__typeInfo, LastModifiedDate, LastModifiedDate__is_set);
       __typeMapper.writeObject(__out, LastReferencedDate__typeInfo, LastReferencedDate, LastReferencedDate__is_set);
       __typeMapper.writeObject(__out, LastViewedDate__typeInfo, LastViewedDate, LastViewedDate__is_set);
       __typeMapper.writeString(__out, MobilePhone__c__typeInfo, MobilePhone__c, MobilePhone__c__is_set);
       __typeMapper.writeString(__out, Name__typeInfo, Name, Name__is_set);
       __typeMapper.writeString(__out, NameUser__c__typeInfo, NameUser__c, NameUser__c__is_set);
       __typeMapper.writeString(__out, Nivel_de_escalado__c__typeInfo, Nivel_de_escalado__c, Nivel_de_escalado__c__is_set);
       __typeMapper.writeObject(__out, Notes__typeInfo, Notes, Notes__is_set);
       __typeMapper.writeObject(__out, NotesAndAttachments__typeInfo, NotesAndAttachments, NotesAndAttachments__is_set);
       __typeMapper.writeObject(__out, Orden__c__typeInfo, Orden__c, Orden__c__is_set);
       __typeMapper.writeString(__out, Phone__c__typeInfo, Phone__c, Phone__c__is_set);
       __typeMapper.writeString(__out, Photo__c__typeInfo, Photo__c, Photo__c__is_set);
       __typeMapper.writeObject(__out, ProcessInstances__typeInfo, ProcessInstances, ProcessInstances__is_set);
       __typeMapper.writeObject(__out, ProcessSteps__typeInfo, ProcessSteps, ProcessSteps__is_set);
       __typeMapper.writeString(__out, Role__c__typeInfo, Role__c, Role__c__is_set);
       __typeMapper.writeObject(__out, ShowPersonalData__c__typeInfo, ShowPersonalData__c, ShowPersonalData__c__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
       __typeMapper.writeString(__out, User__c__typeInfo, User__c, User__c__is_set);
       __typeMapper.writeObject(__out, User__r__typeInfo, User__r, User__r__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, AboutMe__c__typeInfo)) {
            setAboutMe__c(__typeMapper.readString(__in, AboutMe__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AttachedContentDocuments__typeInfo)) {
            setAttachedContentDocuments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, AttachedContentDocuments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Attachments__typeInfo)) {
            setAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Attachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CombinedAttachments__typeInfo)) {
            setCombinedAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, CombinedAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Contact__c__typeInfo)) {
            setContact__c(__typeMapper.readString(__in, Contact__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Contact__r__typeInfo)) {
            setContact__r((com.sforce.soap.enterprise.sobject.Contact)__typeMapper.readObject(__in, Contact__r__typeInfo, com.sforce.soap.enterprise.sobject.Contact.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Delete__c__typeInfo)) {
            setDelete__c((java.lang.Boolean)__typeMapper.readObject(__in, Delete__c__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DependentUserName__c__typeInfo)) {
            setDependentUserName__c(__typeMapper.readString(__in, DependentUserName__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DependentUser__c__typeInfo)) {
            setDependentUser__c(__typeMapper.readString(__in, DependentUser__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DependentUser__r__typeInfo)) {
            setDependentUser__r((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, DependentUser__r__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Description__c__typeInfo)) {
            setDescription__c(__typeMapper.readString(__in, Description__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Email__c__typeInfo)) {
            setEmail__c(__typeMapper.readString(__in, Email__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FeedSubscriptionsForEntity__typeInfo)) {
            setFeedSubscriptionsForEntity((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, FeedSubscriptionsForEntity__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedBy__typeInfo)) {
            setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, LastModifiedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedById__typeInfo)) {
            setLastModifiedById(__typeMapper.readString(__in, LastModifiedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedDate__typeInfo)) {
            setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, LastModifiedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastReferencedDate__typeInfo)) {
            setLastReferencedDate((java.util.Calendar)__typeMapper.readObject(__in, LastReferencedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastViewedDate__typeInfo)) {
            setLastViewedDate((java.util.Calendar)__typeMapper.readObject(__in, LastViewedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, MobilePhone__c__typeInfo)) {
            setMobilePhone__c(__typeMapper.readString(__in, MobilePhone__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Name__typeInfo)) {
            setName(__typeMapper.readString(__in, Name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NameUser__c__typeInfo)) {
            setNameUser__c(__typeMapper.readString(__in, NameUser__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Nivel_de_escalado__c__typeInfo)) {
            setNivel_de_escalado__c(__typeMapper.readString(__in, Nivel_de_escalado__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Notes__typeInfo)) {
            setNotes((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Notes__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NotesAndAttachments__typeInfo)) {
            setNotesAndAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, NotesAndAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Orden__c__typeInfo)) {
            setOrden__c((java.lang.Double)__typeMapper.readObject(__in, Orden__c__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Phone__c__typeInfo)) {
            setPhone__c(__typeMapper.readString(__in, Phone__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Photo__c__typeInfo)) {
            setPhoto__c(__typeMapper.readString(__in, Photo__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessInstances__typeInfo)) {
            setProcessInstances((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessInstances__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessSteps__typeInfo)) {
            setProcessSteps((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessSteps__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Role__c__typeInfo)) {
            setRole__c(__typeMapper.readString(__in, Role__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShowPersonalData__c__typeInfo)) {
            setShowPersonalData__c((java.lang.Boolean)__typeMapper.readObject(__in, ShowPersonalData__c__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, User__c__typeInfo)) {
            setUser__c(__typeMapper.readString(__in, User__c__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, User__r__typeInfo)) {
            setUser__r((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, User__r__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Hierarchy__c ");
      sb.append(super.toString());sb.append(" AboutMe__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AboutMe__c)+"'\n");
      sb.append(" AttachedContentDocuments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AttachedContentDocuments)+"'\n");
      sb.append(" Attachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Attachments)+"'\n");
      sb.append(" CombinedAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CombinedAttachments)+"'\n");
      sb.append(" Contact__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Contact__c)+"'\n");
      sb.append(" Contact__r=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Contact__r)+"'\n");
      sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" Delete__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Delete__c)+"'\n");
      sb.append(" DependentUserName__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(DependentUserName__c)+"'\n");
      sb.append(" DependentUser__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(DependentUser__c)+"'\n");
      sb.append(" DependentUser__r=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(DependentUser__r)+"'\n");
      sb.append(" Description__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Description__c)+"'\n");
      sb.append(" Email__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Email__c)+"'\n");
      sb.append(" FeedSubscriptionsForEntity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(FeedSubscriptionsForEntity)+"'\n");
      sb.append(" IsDeleted=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsDeleted)+"'\n");
      sb.append(" LastModifiedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedBy)+"'\n");
      sb.append(" LastModifiedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedById)+"'\n");
      sb.append(" LastModifiedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedDate)+"'\n");
      sb.append(" LastReferencedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastReferencedDate)+"'\n");
      sb.append(" LastViewedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastViewedDate)+"'\n");
      sb.append(" MobilePhone__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(MobilePhone__c)+"'\n");
      sb.append(" Name=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Name)+"'\n");
      sb.append(" NameUser__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NameUser__c)+"'\n");
      sb.append(" Nivel_de_escalado__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Nivel_de_escalado__c)+"'\n");
      sb.append(" Notes=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Notes)+"'\n");
      sb.append(" NotesAndAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NotesAndAttachments)+"'\n");
      sb.append(" Orden__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Orden__c)+"'\n");
      sb.append(" Phone__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Phone__c)+"'\n");
      sb.append(" Photo__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Photo__c)+"'\n");
      sb.append(" ProcessInstances=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessInstances)+"'\n");
      sb.append(" ProcessSteps=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessSteps)+"'\n");
      sb.append(" Role__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Role__c)+"'\n");
      sb.append(" ShowPersonalData__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShowPersonalData__c)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append(" User__c=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(User__c)+"'\n");
      sb.append(" User__r=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(User__r)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
