package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class KnowledgeArticleVersionHistory extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public KnowledgeArticleVersionHistory() {}

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : EventType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo EventType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EventType","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean EventType__is_set = false;

    private java.lang.String EventType;

    public java.lang.String getEventType() {
      return EventType;
    }

    public void setEventType(java.lang.String EventType) {
      this.EventType = EventType;
      EventType__is_set = true;
    }

    /**
     * element : FieldName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo FieldName__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FieldName","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean FieldName__is_set = false;

    private java.lang.String FieldName;

    public java.lang.String getFieldName() {
      return FieldName;
    }

    public void setFieldName(java.lang.String FieldName) {
      this.FieldName = FieldName;
      FieldName__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : Language of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Language__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Language","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Language__is_set = false;

    private java.lang.String Language;

    public java.lang.String getLanguage() {
      return Language;
    }

    public void setLanguage(java.lang.String Language) {
      this.Language = Language;
      Language__is_set = true;
    }

    /**
     * element : NewValue of type {http://www.w3.org/2001/XMLSchema}anyType
     * java type: java.lang.Object
     */
    private static final com.sforce.ws.bind.TypeInfo NewValue__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NewValue","http://www.w3.org/2001/XMLSchema","anyType",0,1,true);

    private boolean NewValue__is_set = false;

    private java.lang.Object NewValue;

    public java.lang.Object getNewValue() {
      return NewValue;
    }

    public void setNewValue(java.lang.Object NewValue) {
      this.NewValue = NewValue;
      NewValue__is_set = true;
    }

    /**
     * element : OldValue of type {http://www.w3.org/2001/XMLSchema}anyType
     * java type: java.lang.Object
     */
    private static final com.sforce.ws.bind.TypeInfo OldValue__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OldValue","http://www.w3.org/2001/XMLSchema","anyType",0,1,true);

    private boolean OldValue__is_set = false;

    private java.lang.Object OldValue;

    public java.lang.Object getOldValue() {
      return OldValue;
    }

    public void setOldValue(java.lang.Object OldValue) {
      this.OldValue = OldValue;
      OldValue__is_set = true;
    }

    /**
     * element : Parent of type {urn:sobject.enterprise.soap.sforce.com}KnowledgeArticle
     * java type: com.sforce.soap.enterprise.sobject.KnowledgeArticle
     */
    private static final com.sforce.ws.bind.TypeInfo Parent__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Parent","urn:sobject.enterprise.soap.sforce.com","KnowledgeArticle",0,1,true);

    private boolean Parent__is_set = false;

    private com.sforce.soap.enterprise.sobject.KnowledgeArticle Parent;

    public com.sforce.soap.enterprise.sobject.KnowledgeArticle getParent() {
      return Parent;
    }

    public void setParent(com.sforce.soap.enterprise.sobject.KnowledgeArticle Parent) {
      this.Parent = Parent;
      Parent__is_set = true;
    }

    /**
     * element : ParentId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ParentId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ParentId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ParentId__is_set = false;

    private java.lang.String ParentId;

    public java.lang.String getParentId() {
      return ParentId;
    }

    public void setParentId(java.lang.String ParentId) {
      this.ParentId = ParentId;
      ParentId__is_set = true;
    }

    /**
     * element : ParentSobjectType of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ParentSobjectType__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ParentSobjectType","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ParentSobjectType__is_set = false;

    private java.lang.String ParentSobjectType;

    public java.lang.String getParentSobjectType() {
      return ParentSobjectType;
    }

    public void setParentSobjectType(java.lang.String ParentSobjectType) {
      this.ParentSobjectType = ParentSobjectType;
      ParentSobjectType__is_set = true;
    }

    /**
     * element : Version of type {urn:sobject.enterprise.soap.sforce.com}FAQ__kav
     * java type: com.sforce.soap.enterprise.sobject.FAQ__kav
     */
    private static final com.sforce.ws.bind.TypeInfo Version__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Version","urn:sobject.enterprise.soap.sforce.com","FAQ__kav",0,1,true);

    private boolean Version__is_set = false;

    private com.sforce.soap.enterprise.sobject.FAQ__kav Version;

    public com.sforce.soap.enterprise.sobject.FAQ__kav getVersion() {
      return Version;
    }

    public void setVersion(com.sforce.soap.enterprise.sobject.FAQ__kav Version) {
      this.Version = Version;
      Version__is_set = true;
    }

    /**
     * element : VersionId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo VersionId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","VersionId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean VersionId__is_set = false;

    private java.lang.String VersionId;

    public java.lang.String getVersionId() {
      return VersionId;
    }

    public void setVersionId(java.lang.String VersionId) {
      this.VersionId = VersionId;
      VersionId__is_set = true;
    }

    /**
     * element : VersionNumber of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo VersionNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","VersionNumber","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean VersionNumber__is_set = false;

    private java.lang.Integer VersionNumber;

    public java.lang.Integer getVersionNumber() {
      return VersionNumber;
    }

    public void setVersionNumber(java.lang.Integer VersionNumber) {
      this.VersionNumber = VersionNumber;
      VersionNumber__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "KnowledgeArticleVersionHistory");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeString(__out, EventType__typeInfo, EventType, EventType__is_set);
       __typeMapper.writeString(__out, FieldName__typeInfo, FieldName, FieldName__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeString(__out, Language__typeInfo, Language, Language__is_set);
       __typeMapper.writeObject(__out, NewValue__typeInfo, NewValue, NewValue__is_set);
       __typeMapper.writeObject(__out, OldValue__typeInfo, OldValue, OldValue__is_set);
       __typeMapper.writeObject(__out, Parent__typeInfo, Parent, Parent__is_set);
       __typeMapper.writeString(__out, ParentId__typeInfo, ParentId, ParentId__is_set);
       __typeMapper.writeString(__out, ParentSobjectType__typeInfo, ParentSobjectType, ParentSobjectType__is_set);
       __typeMapper.writeObject(__out, Version__typeInfo, Version, Version__is_set);
       __typeMapper.writeString(__out, VersionId__typeInfo, VersionId, VersionId__is_set);
       __typeMapper.writeObject(__out, VersionNumber__typeInfo, VersionNumber, VersionNumber__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EventType__typeInfo)) {
            setEventType(__typeMapper.readString(__in, EventType__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FieldName__typeInfo)) {
            setFieldName(__typeMapper.readString(__in, FieldName__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Language__typeInfo)) {
            setLanguage(__typeMapper.readString(__in, Language__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NewValue__typeInfo)) {
            setNewValue((java.lang.Object)__typeMapper.readObject(__in, NewValue__typeInfo, java.lang.Object.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OldValue__typeInfo)) {
            setOldValue((java.lang.Object)__typeMapper.readObject(__in, OldValue__typeInfo, java.lang.Object.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Parent__typeInfo)) {
            setParent((com.sforce.soap.enterprise.sobject.KnowledgeArticle)__typeMapper.readObject(__in, Parent__typeInfo, com.sforce.soap.enterprise.sobject.KnowledgeArticle.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ParentId__typeInfo)) {
            setParentId(__typeMapper.readString(__in, ParentId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ParentSobjectType__typeInfo)) {
            setParentSobjectType(__typeMapper.readString(__in, ParentSobjectType__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Version__typeInfo)) {
            setVersion((com.sforce.soap.enterprise.sobject.FAQ__kav)__typeMapper.readObject(__in, Version__typeInfo, com.sforce.soap.enterprise.sobject.FAQ__kav.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, VersionId__typeInfo)) {
            setVersionId(__typeMapper.readString(__in, VersionId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, VersionNumber__typeInfo)) {
            setVersionNumber((java.lang.Integer)__typeMapper.readObject(__in, VersionNumber__typeInfo, java.lang.Integer.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[KnowledgeArticleVersionHistory ");
      sb.append(super.toString());sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" EventType=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(EventType)+"'\n");
      sb.append(" FieldName=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(FieldName)+"'\n");
      sb.append(" IsDeleted=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsDeleted)+"'\n");
      sb.append(" Language=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Language)+"'\n");
      sb.append(" NewValue=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NewValue)+"'\n");
      sb.append(" OldValue=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OldValue)+"'\n");
      sb.append(" Parent=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Parent)+"'\n");
      sb.append(" ParentId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ParentId)+"'\n");
      sb.append(" ParentSobjectType=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ParentSobjectType)+"'\n");
      sb.append(" Version=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Version)+"'\n");
      sb.append(" VersionId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(VersionId)+"'\n");
      sb.append(" VersionNumber=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(VersionNumber)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
