package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class NetworkMember extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public NetworkMember() {}

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : DefaultGroupNotificationFrequency of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo DefaultGroupNotificationFrequency__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DefaultGroupNotificationFrequency","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean DefaultGroupNotificationFrequency__is_set = false;

    private java.lang.String DefaultGroupNotificationFrequency;

    public java.lang.String getDefaultGroupNotificationFrequency() {
      return DefaultGroupNotificationFrequency;
    }

    public void setDefaultGroupNotificationFrequency(java.lang.String DefaultGroupNotificationFrequency) {
      this.DefaultGroupNotificationFrequency = DefaultGroupNotificationFrequency;
      DefaultGroupNotificationFrequency__is_set = true;
    }

    /**
     * element : DigestFrequency of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo DigestFrequency__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","DigestFrequency","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean DigestFrequency__is_set = false;

    private java.lang.String DigestFrequency;

    public java.lang.String getDigestFrequency() {
      return DigestFrequency;
    }

    public void setDigestFrequency(java.lang.String DigestFrequency) {
      this.DigestFrequency = DigestFrequency;
      DigestFrequency__is_set = true;
    }

    /**
     * element : Member of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo Member__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Member","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean Member__is_set = false;

    private com.sforce.soap.enterprise.sobject.User Member;

    public com.sforce.soap.enterprise.sobject.User getMember() {
      return Member;
    }

    public void setMember(com.sforce.soap.enterprise.sobject.User Member) {
      this.Member = Member;
      Member__is_set = true;
    }

    /**
     * element : MemberId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo MemberId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","MemberId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean MemberId__is_set = false;

    private java.lang.String MemberId;

    public java.lang.String getMemberId() {
      return MemberId;
    }

    public void setMemberId(java.lang.String MemberId) {
      this.MemberId = MemberId;
      MemberId__is_set = true;
    }

    /**
     * element : Network of type {urn:sobject.enterprise.soap.sforce.com}Network
     * java type: com.sforce.soap.enterprise.sobject.Network
     */
    private static final com.sforce.ws.bind.TypeInfo Network__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Network","urn:sobject.enterprise.soap.sforce.com","Network",0,1,true);

    private boolean Network__is_set = false;

    private com.sforce.soap.enterprise.sobject.Network Network;

    public com.sforce.soap.enterprise.sobject.Network getNetwork() {
      return Network;
    }

    public void setNetwork(com.sforce.soap.enterprise.sobject.Network Network) {
      this.Network = Network;
      Network__is_set = true;
    }

    /**
     * element : NetworkId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo NetworkId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NetworkId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean NetworkId__is_set = false;

    private java.lang.String NetworkId;

    public java.lang.String getNetworkId() {
      return NetworkId;
    }

    public void setNetworkId(java.lang.String NetworkId) {
      this.NetworkId = NetworkId;
      NetworkId__is_set = true;
    }

    /**
     * element : PreferencesDisCommentAfterLikeEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisCommentAfterLikeEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisCommentAfterLikeEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisCommentAfterLikeEmail__is_set = false;

    private java.lang.Boolean PreferencesDisCommentAfterLikeEmail;

    public java.lang.Boolean getPreferencesDisCommentAfterLikeEmail() {
      return PreferencesDisCommentAfterLikeEmail;
    }

    public void setPreferencesDisCommentAfterLikeEmail(java.lang.Boolean PreferencesDisCommentAfterLikeEmail) {
      this.PreferencesDisCommentAfterLikeEmail = PreferencesDisCommentAfterLikeEmail;
      PreferencesDisCommentAfterLikeEmail__is_set = true;
    }

    /**
     * element : PreferencesDisMentionsCommentEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisMentionsCommentEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisMentionsCommentEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisMentionsCommentEmail__is_set = false;

    private java.lang.Boolean PreferencesDisMentionsCommentEmail;

    public java.lang.Boolean getPreferencesDisMentionsCommentEmail() {
      return PreferencesDisMentionsCommentEmail;
    }

    public void setPreferencesDisMentionsCommentEmail(java.lang.Boolean PreferencesDisMentionsCommentEmail) {
      this.PreferencesDisMentionsCommentEmail = PreferencesDisMentionsCommentEmail;
      PreferencesDisMentionsCommentEmail__is_set = true;
    }

    /**
     * element : PreferencesDisProfPostCommentEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisProfPostCommentEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisProfPostCommentEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisProfPostCommentEmail__is_set = false;

    private java.lang.Boolean PreferencesDisProfPostCommentEmail;

    public java.lang.Boolean getPreferencesDisProfPostCommentEmail() {
      return PreferencesDisProfPostCommentEmail;
    }

    public void setPreferencesDisProfPostCommentEmail(java.lang.Boolean PreferencesDisProfPostCommentEmail) {
      this.PreferencesDisProfPostCommentEmail = PreferencesDisProfPostCommentEmail;
      PreferencesDisProfPostCommentEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableAllFeedsEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableAllFeedsEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableAllFeedsEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableAllFeedsEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableAllFeedsEmail;

    public java.lang.Boolean getPreferencesDisableAllFeedsEmail() {
      return PreferencesDisableAllFeedsEmail;
    }

    public void setPreferencesDisableAllFeedsEmail(java.lang.Boolean PreferencesDisableAllFeedsEmail) {
      this.PreferencesDisableAllFeedsEmail = PreferencesDisableAllFeedsEmail;
      PreferencesDisableAllFeedsEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableBookmarkEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableBookmarkEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableBookmarkEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableBookmarkEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableBookmarkEmail;

    public java.lang.Boolean getPreferencesDisableBookmarkEmail() {
      return PreferencesDisableBookmarkEmail;
    }

    public void setPreferencesDisableBookmarkEmail(java.lang.Boolean PreferencesDisableBookmarkEmail) {
      this.PreferencesDisableBookmarkEmail = PreferencesDisableBookmarkEmail;
      PreferencesDisableBookmarkEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableChangeCommentEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableChangeCommentEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableChangeCommentEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableChangeCommentEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableChangeCommentEmail;

    public java.lang.Boolean getPreferencesDisableChangeCommentEmail() {
      return PreferencesDisableChangeCommentEmail;
    }

    public void setPreferencesDisableChangeCommentEmail(java.lang.Boolean PreferencesDisableChangeCommentEmail) {
      this.PreferencesDisableChangeCommentEmail = PreferencesDisableChangeCommentEmail;
      PreferencesDisableChangeCommentEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableFollowersEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableFollowersEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableFollowersEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableFollowersEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableFollowersEmail;

    public java.lang.Boolean getPreferencesDisableFollowersEmail() {
      return PreferencesDisableFollowersEmail;
    }

    public void setPreferencesDisableFollowersEmail(java.lang.Boolean PreferencesDisableFollowersEmail) {
      this.PreferencesDisableFollowersEmail = PreferencesDisableFollowersEmail;
      PreferencesDisableFollowersEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableItemFlaggedEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableItemFlaggedEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableItemFlaggedEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableItemFlaggedEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableItemFlaggedEmail;

    public java.lang.Boolean getPreferencesDisableItemFlaggedEmail() {
      return PreferencesDisableItemFlaggedEmail;
    }

    public void setPreferencesDisableItemFlaggedEmail(java.lang.Boolean PreferencesDisableItemFlaggedEmail) {
      this.PreferencesDisableItemFlaggedEmail = PreferencesDisableItemFlaggedEmail;
      PreferencesDisableItemFlaggedEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableLaterCommentEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableLaterCommentEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableLaterCommentEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableLaterCommentEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableLaterCommentEmail;

    public java.lang.Boolean getPreferencesDisableLaterCommentEmail() {
      return PreferencesDisableLaterCommentEmail;
    }

    public void setPreferencesDisableLaterCommentEmail(java.lang.Boolean PreferencesDisableLaterCommentEmail) {
      this.PreferencesDisableLaterCommentEmail = PreferencesDisableLaterCommentEmail;
      PreferencesDisableLaterCommentEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableLikeEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableLikeEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableLikeEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableLikeEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableLikeEmail;

    public java.lang.Boolean getPreferencesDisableLikeEmail() {
      return PreferencesDisableLikeEmail;
    }

    public void setPreferencesDisableLikeEmail(java.lang.Boolean PreferencesDisableLikeEmail) {
      this.PreferencesDisableLikeEmail = PreferencesDisableLikeEmail;
      PreferencesDisableLikeEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableMentionsPostEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableMentionsPostEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableMentionsPostEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableMentionsPostEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableMentionsPostEmail;

    public java.lang.Boolean getPreferencesDisableMentionsPostEmail() {
      return PreferencesDisableMentionsPostEmail;
    }

    public void setPreferencesDisableMentionsPostEmail(java.lang.Boolean PreferencesDisableMentionsPostEmail) {
      this.PreferencesDisableMentionsPostEmail = PreferencesDisableMentionsPostEmail;
      PreferencesDisableMentionsPostEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableProfilePostEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableProfilePostEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableProfilePostEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableProfilePostEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableProfilePostEmail;

    public java.lang.Boolean getPreferencesDisableProfilePostEmail() {
      return PreferencesDisableProfilePostEmail;
    }

    public void setPreferencesDisableProfilePostEmail(java.lang.Boolean PreferencesDisableProfilePostEmail) {
      this.PreferencesDisableProfilePostEmail = PreferencesDisableProfilePostEmail;
      PreferencesDisableProfilePostEmail__is_set = true;
    }

    /**
     * element : PreferencesDisableSharePostEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo PreferencesDisableSharePostEmail__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","PreferencesDisableSharePostEmail","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean PreferencesDisableSharePostEmail__is_set = false;

    private java.lang.Boolean PreferencesDisableSharePostEmail;

    public java.lang.Boolean getPreferencesDisableSharePostEmail() {
      return PreferencesDisableSharePostEmail;
    }

    public void setPreferencesDisableSharePostEmail(java.lang.Boolean PreferencesDisableSharePostEmail) {
      this.PreferencesDisableSharePostEmail = PreferencesDisableSharePostEmail;
      PreferencesDisableSharePostEmail__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "NetworkMember");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeString(__out, DefaultGroupNotificationFrequency__typeInfo, DefaultGroupNotificationFrequency, DefaultGroupNotificationFrequency__is_set);
       __typeMapper.writeString(__out, DigestFrequency__typeInfo, DigestFrequency, DigestFrequency__is_set);
       __typeMapper.writeObject(__out, Member__typeInfo, Member, Member__is_set);
       __typeMapper.writeString(__out, MemberId__typeInfo, MemberId, MemberId__is_set);
       __typeMapper.writeObject(__out, Network__typeInfo, Network, Network__is_set);
       __typeMapper.writeString(__out, NetworkId__typeInfo, NetworkId, NetworkId__is_set);
       __typeMapper.writeObject(__out, PreferencesDisCommentAfterLikeEmail__typeInfo, PreferencesDisCommentAfterLikeEmail, PreferencesDisCommentAfterLikeEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisMentionsCommentEmail__typeInfo, PreferencesDisMentionsCommentEmail, PreferencesDisMentionsCommentEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisProfPostCommentEmail__typeInfo, PreferencesDisProfPostCommentEmail, PreferencesDisProfPostCommentEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableAllFeedsEmail__typeInfo, PreferencesDisableAllFeedsEmail, PreferencesDisableAllFeedsEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableBookmarkEmail__typeInfo, PreferencesDisableBookmarkEmail, PreferencesDisableBookmarkEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableChangeCommentEmail__typeInfo, PreferencesDisableChangeCommentEmail, PreferencesDisableChangeCommentEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableFollowersEmail__typeInfo, PreferencesDisableFollowersEmail, PreferencesDisableFollowersEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableItemFlaggedEmail__typeInfo, PreferencesDisableItemFlaggedEmail, PreferencesDisableItemFlaggedEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableLaterCommentEmail__typeInfo, PreferencesDisableLaterCommentEmail, PreferencesDisableLaterCommentEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableLikeEmail__typeInfo, PreferencesDisableLikeEmail, PreferencesDisableLikeEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableMentionsPostEmail__typeInfo, PreferencesDisableMentionsPostEmail, PreferencesDisableMentionsPostEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableProfilePostEmail__typeInfo, PreferencesDisableProfilePostEmail, PreferencesDisableProfilePostEmail__is_set);
       __typeMapper.writeObject(__out, PreferencesDisableSharePostEmail__typeInfo, PreferencesDisableSharePostEmail, PreferencesDisableSharePostEmail__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DefaultGroupNotificationFrequency__typeInfo)) {
            setDefaultGroupNotificationFrequency(__typeMapper.readString(__in, DefaultGroupNotificationFrequency__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, DigestFrequency__typeInfo)) {
            setDigestFrequency(__typeMapper.readString(__in, DigestFrequency__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Member__typeInfo)) {
            setMember((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, Member__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, MemberId__typeInfo)) {
            setMemberId(__typeMapper.readString(__in, MemberId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Network__typeInfo)) {
            setNetwork((com.sforce.soap.enterprise.sobject.Network)__typeMapper.readObject(__in, Network__typeInfo, com.sforce.soap.enterprise.sobject.Network.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NetworkId__typeInfo)) {
            setNetworkId(__typeMapper.readString(__in, NetworkId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisCommentAfterLikeEmail__typeInfo)) {
            setPreferencesDisCommentAfterLikeEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisCommentAfterLikeEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisMentionsCommentEmail__typeInfo)) {
            setPreferencesDisMentionsCommentEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisMentionsCommentEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisProfPostCommentEmail__typeInfo)) {
            setPreferencesDisProfPostCommentEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisProfPostCommentEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableAllFeedsEmail__typeInfo)) {
            setPreferencesDisableAllFeedsEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableAllFeedsEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableBookmarkEmail__typeInfo)) {
            setPreferencesDisableBookmarkEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableBookmarkEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableChangeCommentEmail__typeInfo)) {
            setPreferencesDisableChangeCommentEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableChangeCommentEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableFollowersEmail__typeInfo)) {
            setPreferencesDisableFollowersEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableFollowersEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableItemFlaggedEmail__typeInfo)) {
            setPreferencesDisableItemFlaggedEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableItemFlaggedEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableLaterCommentEmail__typeInfo)) {
            setPreferencesDisableLaterCommentEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableLaterCommentEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableLikeEmail__typeInfo)) {
            setPreferencesDisableLikeEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableLikeEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableMentionsPostEmail__typeInfo)) {
            setPreferencesDisableMentionsPostEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableMentionsPostEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableProfilePostEmail__typeInfo)) {
            setPreferencesDisableProfilePostEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableProfilePostEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, PreferencesDisableSharePostEmail__typeInfo)) {
            setPreferencesDisableSharePostEmail((java.lang.Boolean)__typeMapper.readObject(__in, PreferencesDisableSharePostEmail__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[NetworkMember ");
      sb.append(super.toString());sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" DefaultGroupNotificationFrequency=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(DefaultGroupNotificationFrequency)+"'\n");
      sb.append(" DigestFrequency=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(DigestFrequency)+"'\n");
      sb.append(" Member=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Member)+"'\n");
      sb.append(" MemberId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(MemberId)+"'\n");
      sb.append(" Network=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Network)+"'\n");
      sb.append(" NetworkId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NetworkId)+"'\n");
      sb.append(" PreferencesDisCommentAfterLikeEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisCommentAfterLikeEmail)+"'\n");
      sb.append(" PreferencesDisMentionsCommentEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisMentionsCommentEmail)+"'\n");
      sb.append(" PreferencesDisProfPostCommentEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisProfPostCommentEmail)+"'\n");
      sb.append(" PreferencesDisableAllFeedsEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableAllFeedsEmail)+"'\n");
      sb.append(" PreferencesDisableBookmarkEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableBookmarkEmail)+"'\n");
      sb.append(" PreferencesDisableChangeCommentEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableChangeCommentEmail)+"'\n");
      sb.append(" PreferencesDisableFollowersEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableFollowersEmail)+"'\n");
      sb.append(" PreferencesDisableItemFlaggedEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableItemFlaggedEmail)+"'\n");
      sb.append(" PreferencesDisableLaterCommentEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableLaterCommentEmail)+"'\n");
      sb.append(" PreferencesDisableLikeEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableLikeEmail)+"'\n");
      sb.append(" PreferencesDisableMentionsPostEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableMentionsPostEmail)+"'\n");
      sb.append(" PreferencesDisableProfilePostEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableProfilePostEmail)+"'\n");
      sb.append(" PreferencesDisableSharePostEmail=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(PreferencesDisableSharePostEmail)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
