package com.sforce.soap.enterprise.sobject;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class ServiceContract extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public ServiceContract() {}

    /**
     * element : Account of type {urn:sobject.enterprise.soap.sforce.com}Account
     * java type: com.sforce.soap.enterprise.sobject.Account
     */
    private static final com.sforce.ws.bind.TypeInfo Account__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true);

    private boolean Account__is_set = false;

    private com.sforce.soap.enterprise.sobject.Account Account;

    public com.sforce.soap.enterprise.sobject.Account getAccount() {
      return Account;
    }

    public void setAccount(com.sforce.soap.enterprise.sobject.Account Account) {
      this.Account = Account;
      Account__is_set = true;
    }

    /**
     * element : AccountId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo AccountId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean AccountId__is_set = false;

    private java.lang.String AccountId;

    public java.lang.String getAccountId() {
      return AccountId;
    }

    public void setAccountId(java.lang.String AccountId) {
      this.AccountId = AccountId;
      AccountId__is_set = true;
    }

    /**
     * element : ActivationDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo ActivationDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivationDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean ActivationDate__is_set = false;

    private java.util.Calendar ActivationDate;

    public java.util.Calendar getActivationDate() {
      return ActivationDate;
    }

    public void setActivationDate(java.util.Calendar ActivationDate) {
      this.ActivationDate = ActivationDate;
      ActivationDate__is_set = true;
    }

    /**
     * element : ActivityHistories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ActivityHistories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ActivityHistories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ActivityHistories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ActivityHistories;

    public com.sforce.soap.enterprise.QueryResult getActivityHistories() {
      return ActivityHistories;
    }

    public void setActivityHistories(com.sforce.soap.enterprise.QueryResult ActivityHistories) {
      this.ActivityHistories = ActivityHistories;
      ActivityHistories__is_set = true;
    }

    /**
     * element : ApprovalStatus of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ApprovalStatus__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ApprovalStatus","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ApprovalStatus__is_set = false;

    private java.lang.String ApprovalStatus;

    public java.lang.String getApprovalStatus() {
      return ApprovalStatus;
    }

    public void setApprovalStatus(java.lang.String ApprovalStatus) {
      this.ApprovalStatus = ApprovalStatus;
      ApprovalStatus__is_set = true;
    }

    /**
     * element : AttachedContentDocuments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo AttachedContentDocuments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","AttachedContentDocuments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean AttachedContentDocuments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult AttachedContentDocuments;

    public com.sforce.soap.enterprise.QueryResult getAttachedContentDocuments() {
      return AttachedContentDocuments;
    }

    public void setAttachedContentDocuments(com.sforce.soap.enterprise.QueryResult AttachedContentDocuments) {
      this.AttachedContentDocuments = AttachedContentDocuments;
      AttachedContentDocuments__is_set = true;
    }

    /**
     * element : Attachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Attachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Attachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Attachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Attachments;

    public com.sforce.soap.enterprise.QueryResult getAttachments() {
      return Attachments;
    }

    public void setAttachments(com.sforce.soap.enterprise.QueryResult Attachments) {
      this.Attachments = Attachments;
      Attachments__is_set = true;
    }

    /**
     * element : BillingCity of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingCity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingCity","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingCity__is_set = false;

    private java.lang.String BillingCity;

    public java.lang.String getBillingCity() {
      return BillingCity;
    }

    public void setBillingCity(java.lang.String BillingCity) {
      this.BillingCity = BillingCity;
      BillingCity__is_set = true;
    }

    /**
     * element : BillingCountry of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingCountry__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingCountry","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingCountry__is_set = false;

    private java.lang.String BillingCountry;

    public java.lang.String getBillingCountry() {
      return BillingCountry;
    }

    public void setBillingCountry(java.lang.String BillingCountry) {
      this.BillingCountry = BillingCountry;
      BillingCountry__is_set = true;
    }

    /**
     * element : BillingLatitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo BillingLatitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingLatitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean BillingLatitude__is_set = false;

    private java.lang.Double BillingLatitude;

    public java.lang.Double getBillingLatitude() {
      return BillingLatitude;
    }

    public void setBillingLatitude(java.lang.Double BillingLatitude) {
      this.BillingLatitude = BillingLatitude;
      BillingLatitude__is_set = true;
    }

    /**
     * element : BillingLongitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo BillingLongitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingLongitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean BillingLongitude__is_set = false;

    private java.lang.Double BillingLongitude;

    public java.lang.Double getBillingLongitude() {
      return BillingLongitude;
    }

    public void setBillingLongitude(java.lang.Double BillingLongitude) {
      this.BillingLongitude = BillingLongitude;
      BillingLongitude__is_set = true;
    }

    /**
     * element : BillingPostalCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingPostalCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingPostalCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingPostalCode__is_set = false;

    private java.lang.String BillingPostalCode;

    public java.lang.String getBillingPostalCode() {
      return BillingPostalCode;
    }

    public void setBillingPostalCode(java.lang.String BillingPostalCode) {
      this.BillingPostalCode = BillingPostalCode;
      BillingPostalCode__is_set = true;
    }

    /**
     * element : BillingState of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingState__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingState","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingState__is_set = false;

    private java.lang.String BillingState;

    public java.lang.String getBillingState() {
      return BillingState;
    }

    public void setBillingState(java.lang.String BillingState) {
      this.BillingState = BillingState;
      BillingState__is_set = true;
    }

    /**
     * element : BillingStreet of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo BillingStreet__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","BillingStreet","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean BillingStreet__is_set = false;

    private java.lang.String BillingStreet;

    public java.lang.String getBillingStreet() {
      return BillingStreet;
    }

    public void setBillingStreet(java.lang.String BillingStreet) {
      this.BillingStreet = BillingStreet;
      BillingStreet__is_set = true;
    }

    /**
     * element : CombinedAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo CombinedAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CombinedAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean CombinedAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult CombinedAttachments;

    public com.sforce.soap.enterprise.QueryResult getCombinedAttachments() {
      return CombinedAttachments;
    }

    public void setCombinedAttachments(com.sforce.soap.enterprise.QueryResult CombinedAttachments) {
      this.CombinedAttachments = CombinedAttachments;
      CombinedAttachments__is_set = true;
    }

    /**
     * element : Contact of type {urn:sobject.enterprise.soap.sforce.com}Contact
     * java type: com.sforce.soap.enterprise.sobject.Contact
     */
    private static final com.sforce.ws.bind.TypeInfo Contact__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Contact","urn:sobject.enterprise.soap.sforce.com","Contact",0,1,true);

    private boolean Contact__is_set = false;

    private com.sforce.soap.enterprise.sobject.Contact Contact;

    public com.sforce.soap.enterprise.sobject.Contact getContact() {
      return Contact;
    }

    public void setContact(com.sforce.soap.enterprise.sobject.Contact Contact) {
      this.Contact = Contact;
      Contact__is_set = true;
    }

    /**
     * element : ContactId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ContactId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContactId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean ContactId__is_set = false;

    private java.lang.String ContactId;

    public java.lang.String getContactId() {
      return ContactId;
    }

    public void setContactId(java.lang.String ContactId) {
      this.ContactId = ContactId;
      ContactId__is_set = true;
    }

    /**
     * element : ContractLineItems of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ContractLineItems__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContractLineItems","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ContractLineItems__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ContractLineItems;

    public com.sforce.soap.enterprise.QueryResult getContractLineItems() {
      return ContractLineItems;
    }

    public void setContractLineItems(com.sforce.soap.enterprise.QueryResult ContractLineItems) {
      this.ContractLineItems = ContractLineItems;
      ContractLineItems__is_set = true;
    }

    /**
     * element : ContractNumber of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ContractNumber__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ContractNumber","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ContractNumber__is_set = false;

    private java.lang.String ContractNumber;

    public java.lang.String getContractNumber() {
      return ContractNumber;
    }

    public void setContractNumber(java.lang.String ContractNumber) {
      this.ContractNumber = ContractNumber;
      ContractNumber__is_set = true;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo CreatedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    /**
     * element : Description of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Description__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Description","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Description__is_set = false;

    private java.lang.String Description;

    public java.lang.String getDescription() {
      return Description;
    }

    public void setDescription(java.lang.String Description) {
      this.Description = Description;
      Description__is_set = true;
    }

    /**
     * element : Discount of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo Discount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Discount","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean Discount__is_set = false;

    private java.lang.Double Discount;

    public java.lang.Double getDiscount() {
      return Discount;
    }

    public void setDiscount(java.lang.Double Discount) {
      this.Discount = Discount;
      Discount__is_set = true;
    }

    /**
     * element : EndDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo EndDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","EndDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean EndDate__is_set = false;

    private java.util.Calendar EndDate;

    public java.util.Calendar getEndDate() {
      return EndDate;
    }

    public void setEndDate(java.util.Calendar EndDate) {
      this.EndDate = EndDate;
      EndDate__is_set = true;
    }

    /**
     * element : Entitlements of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Entitlements__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Entitlements","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Entitlements__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Entitlements;

    public com.sforce.soap.enterprise.QueryResult getEntitlements() {
      return Entitlements;
    }

    public void setEntitlements(com.sforce.soap.enterprise.QueryResult Entitlements) {
      this.Entitlements = Entitlements;
      Entitlements__is_set = true;
    }

    /**
     * element : Events of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Events__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Events","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Events__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Events;

    public com.sforce.soap.enterprise.QueryResult getEvents() {
      return Events;
    }

    public void setEvents(com.sforce.soap.enterprise.QueryResult Events) {
      this.Events = Events;
      Events__is_set = true;
    }

    /**
     * element : FeedSubscriptionsForEntity of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo FeedSubscriptionsForEntity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","FeedSubscriptionsForEntity","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean FeedSubscriptionsForEntity__is_set = false;

    private com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity;

    public com.sforce.soap.enterprise.QueryResult getFeedSubscriptionsForEntity() {
      return FeedSubscriptionsForEntity;
    }

    public void setFeedSubscriptionsForEntity(com.sforce.soap.enterprise.QueryResult FeedSubscriptionsForEntity) {
      this.FeedSubscriptionsForEntity = FeedSubscriptionsForEntity;
      FeedSubscriptionsForEntity__is_set = true;
    }

    /**
     * element : Feeds of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Feeds__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Feeds","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Feeds__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Feeds;

    public com.sforce.soap.enterprise.QueryResult getFeeds() {
      return Feeds;
    }

    public void setFeeds(com.sforce.soap.enterprise.QueryResult Feeds) {
      this.Feeds = Feeds;
      Feeds__is_set = true;
    }

    /**
     * element : GrandTotal of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo GrandTotal__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","GrandTotal","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean GrandTotal__is_set = false;

    private java.lang.Double GrandTotal;

    public java.lang.Double getGrandTotal() {
      return GrandTotal;
    }

    public void setGrandTotal(java.lang.Double GrandTotal) {
      this.GrandTotal = GrandTotal;
      GrandTotal__is_set = true;
    }

    /**
     * element : Histories of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Histories__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Histories","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Histories__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Histories;

    public com.sforce.soap.enterprise.QueryResult getHistories() {
      return Histories;
    }

    public void setHistories(com.sforce.soap.enterprise.QueryResult Histories) {
      this.Histories = Histories;
      Histories__is_set = true;
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private static final com.sforce.ws.bind.TypeInfo IsDeleted__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true);

    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedBy__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true);

    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedById__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastModifiedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    /**
     * element : LastReferencedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastReferencedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastReferencedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastReferencedDate__is_set = false;

    private java.util.Calendar LastReferencedDate;

    public java.util.Calendar getLastReferencedDate() {
      return LastReferencedDate;
    }

    public void setLastReferencedDate(java.util.Calendar LastReferencedDate) {
      this.LastReferencedDate = LastReferencedDate;
      LastReferencedDate__is_set = true;
    }

    /**
     * element : LastViewedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo LastViewedDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LastViewedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean LastViewedDate__is_set = false;

    private java.util.Calendar LastViewedDate;

    public java.util.Calendar getLastViewedDate() {
      return LastViewedDate;
    }

    public void setLastViewedDate(java.util.Calendar LastViewedDate) {
      this.LastViewedDate = LastViewedDate;
      LastViewedDate__is_set = true;
    }

    /**
     * element : LineItemCount of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo LineItemCount__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","LineItemCount","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean LineItemCount__is_set = false;

    private java.lang.Integer LineItemCount;

    public java.lang.Integer getLineItemCount() {
      return LineItemCount;
    }

    public void setLineItemCount(java.lang.Integer LineItemCount) {
      this.LineItemCount = LineItemCount;
      LineItemCount__is_set = true;
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    /**
     * element : Notes of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Notes__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Notes","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Notes__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Notes;

    public com.sforce.soap.enterprise.QueryResult getNotes() {
      return Notes;
    }

    public void setNotes(com.sforce.soap.enterprise.QueryResult Notes) {
      this.Notes = Notes;
      Notes__is_set = true;
    }

    /**
     * element : NotesAndAttachments of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo NotesAndAttachments__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","NotesAndAttachments","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean NotesAndAttachments__is_set = false;

    private com.sforce.soap.enterprise.QueryResult NotesAndAttachments;

    public com.sforce.soap.enterprise.QueryResult getNotesAndAttachments() {
      return NotesAndAttachments;
    }

    public void setNotesAndAttachments(com.sforce.soap.enterprise.QueryResult NotesAndAttachments) {
      this.NotesAndAttachments = NotesAndAttachments;
      NotesAndAttachments__is_set = true;
    }

    /**
     * element : OpenActivities of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo OpenActivities__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OpenActivities","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean OpenActivities__is_set = false;

    private com.sforce.soap.enterprise.QueryResult OpenActivities;

    public com.sforce.soap.enterprise.QueryResult getOpenActivities() {
      return OpenActivities;
    }

    public void setOpenActivities(com.sforce.soap.enterprise.QueryResult OpenActivities) {
      this.OpenActivities = OpenActivities;
      OpenActivities__is_set = true;
    }

    /**
     * element : Owner of type {urn:sobject.enterprise.soap.sforce.com}Name
     * java type: com.sforce.soap.enterprise.sobject.Name
     */
    private static final com.sforce.ws.bind.TypeInfo Owner__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Owner","urn:sobject.enterprise.soap.sforce.com","Name",0,1,true);

    private boolean Owner__is_set = false;

    private com.sforce.soap.enterprise.sobject.Name Owner;

    public com.sforce.soap.enterprise.sobject.Name getOwner() {
      return Owner;
    }

    public void setOwner(com.sforce.soap.enterprise.sobject.Name Owner) {
      this.Owner = Owner;
      Owner__is_set = true;
    }

    /**
     * element : OwnerId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo OwnerId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean OwnerId__is_set = false;

    private java.lang.String OwnerId;

    public java.lang.String getOwnerId() {
      return OwnerId;
    }

    public void setOwnerId(java.lang.String OwnerId) {
      this.OwnerId = OwnerId;
      OwnerId__is_set = true;
    }

    /**
     * element : Pricebook2 of type {urn:sobject.enterprise.soap.sforce.com}Pricebook2
     * java type: com.sforce.soap.enterprise.sobject.Pricebook2
     */
    private static final com.sforce.ws.bind.TypeInfo Pricebook2__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Pricebook2","urn:sobject.enterprise.soap.sforce.com","Pricebook2",0,1,true);

    private boolean Pricebook2__is_set = false;

    private com.sforce.soap.enterprise.sobject.Pricebook2 Pricebook2;

    public com.sforce.soap.enterprise.sobject.Pricebook2 getPricebook2() {
      return Pricebook2;
    }

    public void setPricebook2(com.sforce.soap.enterprise.sobject.Pricebook2 Pricebook2) {
      this.Pricebook2 = Pricebook2;
      Pricebook2__is_set = true;
    }

    /**
     * element : Pricebook2Id of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Pricebook2Id__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Pricebook2Id","urn:enterprise.soap.sforce.com","ID",0,1,true);

    private boolean Pricebook2Id__is_set = false;

    private java.lang.String Pricebook2Id;

    public java.lang.String getPricebook2Id() {
      return Pricebook2Id;
    }

    public void setPricebook2Id(java.lang.String Pricebook2Id) {
      this.Pricebook2Id = Pricebook2Id;
      Pricebook2Id__is_set = true;
    }

    /**
     * element : ProcessInstances of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessInstances__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessInstances","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessInstances__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessInstances;

    public com.sforce.soap.enterprise.QueryResult getProcessInstances() {
      return ProcessInstances;
    }

    public void setProcessInstances(com.sforce.soap.enterprise.QueryResult ProcessInstances) {
      this.ProcessInstances = ProcessInstances;
      ProcessInstances__is_set = true;
    }

    /**
     * element : ProcessSteps of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo ProcessSteps__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ProcessSteps","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean ProcessSteps__is_set = false;

    private com.sforce.soap.enterprise.QueryResult ProcessSteps;

    public com.sforce.soap.enterprise.QueryResult getProcessSteps() {
      return ProcessSteps;
    }

    public void setProcessSteps(com.sforce.soap.enterprise.QueryResult ProcessSteps) {
      this.ProcessSteps = ProcessSteps;
      ProcessSteps__is_set = true;
    }

    /**
     * element : ShippingCity of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingCity__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingCity","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingCity__is_set = false;

    private java.lang.String ShippingCity;

    public java.lang.String getShippingCity() {
      return ShippingCity;
    }

    public void setShippingCity(java.lang.String ShippingCity) {
      this.ShippingCity = ShippingCity;
      ShippingCity__is_set = true;
    }

    /**
     * element : ShippingCountry of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingCountry__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingCountry","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingCountry__is_set = false;

    private java.lang.String ShippingCountry;

    public java.lang.String getShippingCountry() {
      return ShippingCountry;
    }

    public void setShippingCountry(java.lang.String ShippingCountry) {
      this.ShippingCountry = ShippingCountry;
      ShippingCountry__is_set = true;
    }

    /**
     * element : ShippingHandling of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingHandling__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingHandling","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ShippingHandling__is_set = false;

    private java.lang.Double ShippingHandling;

    public java.lang.Double getShippingHandling() {
      return ShippingHandling;
    }

    public void setShippingHandling(java.lang.Double ShippingHandling) {
      this.ShippingHandling = ShippingHandling;
      ShippingHandling__is_set = true;
    }

    /**
     * element : ShippingLatitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingLatitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingLatitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ShippingLatitude__is_set = false;

    private java.lang.Double ShippingLatitude;

    public java.lang.Double getShippingLatitude() {
      return ShippingLatitude;
    }

    public void setShippingLatitude(java.lang.Double ShippingLatitude) {
      this.ShippingLatitude = ShippingLatitude;
      ShippingLatitude__is_set = true;
    }

    /**
     * element : ShippingLongitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingLongitude__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingLongitude","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean ShippingLongitude__is_set = false;

    private java.lang.Double ShippingLongitude;

    public java.lang.Double getShippingLongitude() {
      return ShippingLongitude;
    }

    public void setShippingLongitude(java.lang.Double ShippingLongitude) {
      this.ShippingLongitude = ShippingLongitude;
      ShippingLongitude__is_set = true;
    }

    /**
     * element : ShippingPostalCode of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingPostalCode__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingPostalCode","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingPostalCode__is_set = false;

    private java.lang.String ShippingPostalCode;

    public java.lang.String getShippingPostalCode() {
      return ShippingPostalCode;
    }

    public void setShippingPostalCode(java.lang.String ShippingPostalCode) {
      this.ShippingPostalCode = ShippingPostalCode;
      ShippingPostalCode__is_set = true;
    }

    /**
     * element : ShippingState of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingState__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingState","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingState__is_set = false;

    private java.lang.String ShippingState;

    public java.lang.String getShippingState() {
      return ShippingState;
    }

    public void setShippingState(java.lang.String ShippingState) {
      this.ShippingState = ShippingState;
      ShippingState__is_set = true;
    }

    /**
     * element : ShippingStreet of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo ShippingStreet__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","ShippingStreet","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean ShippingStreet__is_set = false;

    private java.lang.String ShippingStreet;

    public java.lang.String getShippingStreet() {
      return ShippingStreet;
    }

    public void setShippingStreet(java.lang.String ShippingStreet) {
      this.ShippingStreet = ShippingStreet;
      ShippingStreet__is_set = true;
    }

    /**
     * element : SpecialTerms of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo SpecialTerms__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SpecialTerms","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean SpecialTerms__is_set = false;

    private java.lang.String SpecialTerms;

    public java.lang.String getSpecialTerms() {
      return SpecialTerms;
    }

    public void setSpecialTerms(java.lang.String SpecialTerms) {
      this.SpecialTerms = SpecialTerms;
      SpecialTerms__is_set = true;
    }

    /**
     * element : StartDate of type {http://www.w3.org/2001/XMLSchema}date
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo StartDate__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","StartDate","http://www.w3.org/2001/XMLSchema","date",0,1,true);

    private boolean StartDate__is_set = false;

    private java.util.Calendar StartDate;

    public java.util.Calendar getStartDate() {
      return StartDate;
    }

    public void setStartDate(java.util.Calendar StartDate) {
      this.StartDate = StartDate;
      StartDate__is_set = true;
    }

    /**
     * element : Status of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo Status__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean Status__is_set = false;

    private java.lang.String Status;

    public java.lang.String getStatus() {
      return Status;
    }

    public void setStatus(java.lang.String Status) {
      this.Status = Status;
      Status__is_set = true;
    }

    /**
     * element : Subtotal of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo Subtotal__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Subtotal","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean Subtotal__is_set = false;

    private java.lang.Double Subtotal;

    public java.lang.Double getSubtotal() {
      return Subtotal;
    }

    public void setSubtotal(java.lang.Double Subtotal) {
      this.Subtotal = Subtotal;
      Subtotal__is_set = true;
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private static final com.sforce.ws.bind.TypeInfo SystemModstamp__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true);

    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    /**
     * element : Tasks of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private static final com.sforce.ws.bind.TypeInfo Tasks__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Tasks","urn:enterprise.soap.sforce.com","QueryResult",0,1,true);

    private boolean Tasks__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Tasks;

    public com.sforce.soap.enterprise.QueryResult getTasks() {
      return Tasks;
    }

    public void setTasks(com.sforce.soap.enterprise.QueryResult Tasks) {
      this.Tasks = Tasks;
      Tasks__is_set = true;
    }

    /**
     * element : Tax of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo Tax__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Tax","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean Tax__is_set = false;

    private java.lang.Double Tax;

    public java.lang.Double getTax() {
      return Tax;
    }

    public void setTax(java.lang.Double Tax) {
      this.Tax = Tax;
      Tax__is_set = true;
    }

    /**
     * element : Term of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private static final com.sforce.ws.bind.TypeInfo Term__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","Term","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean Term__is_set = false;

    private java.lang.Integer Term;

    public java.lang.Integer getTerm() {
      return Term;
    }

    public void setTerm(java.lang.Integer Term) {
      this.Term = Term;
      Term__is_set = true;
    }

    /**
     * element : TotalPrice of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private static final com.sforce.ws.bind.TypeInfo TotalPrice__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:sobject.enterprise.soap.sforce.com","TotalPrice","http://www.w3.org/2001/XMLSchema","double",0,1,true);

    private boolean TotalPrice__is_set = false;

    private java.lang.Double TotalPrice;

    public java.lang.Double getTotalPrice() {
      return TotalPrice;
    }

    public void setTotalPrice(java.lang.Double TotalPrice) {
      this.TotalPrice = TotalPrice;
      TotalPrice__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "ServiceContract");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       __typeMapper.writeObject(__out, Account__typeInfo, Account, Account__is_set);
       __typeMapper.writeString(__out, AccountId__typeInfo, AccountId, AccountId__is_set);
       __typeMapper.writeObject(__out, ActivationDate__typeInfo, ActivationDate, ActivationDate__is_set);
       __typeMapper.writeObject(__out, ActivityHistories__typeInfo, ActivityHistories, ActivityHistories__is_set);
       __typeMapper.writeString(__out, ApprovalStatus__typeInfo, ApprovalStatus, ApprovalStatus__is_set);
       __typeMapper.writeObject(__out, AttachedContentDocuments__typeInfo, AttachedContentDocuments, AttachedContentDocuments__is_set);
       __typeMapper.writeObject(__out, Attachments__typeInfo, Attachments, Attachments__is_set);
       __typeMapper.writeString(__out, BillingCity__typeInfo, BillingCity, BillingCity__is_set);
       __typeMapper.writeString(__out, BillingCountry__typeInfo, BillingCountry, BillingCountry__is_set);
       __typeMapper.writeObject(__out, BillingLatitude__typeInfo, BillingLatitude, BillingLatitude__is_set);
       __typeMapper.writeObject(__out, BillingLongitude__typeInfo, BillingLongitude, BillingLongitude__is_set);
       __typeMapper.writeString(__out, BillingPostalCode__typeInfo, BillingPostalCode, BillingPostalCode__is_set);
       __typeMapper.writeString(__out, BillingState__typeInfo, BillingState, BillingState__is_set);
       __typeMapper.writeString(__out, BillingStreet__typeInfo, BillingStreet, BillingStreet__is_set);
       __typeMapper.writeObject(__out, CombinedAttachments__typeInfo, CombinedAttachments, CombinedAttachments__is_set);
       __typeMapper.writeObject(__out, Contact__typeInfo, Contact, Contact__is_set);
       __typeMapper.writeString(__out, ContactId__typeInfo, ContactId, ContactId__is_set);
       __typeMapper.writeObject(__out, ContractLineItems__typeInfo, ContractLineItems, ContractLineItems__is_set);
       __typeMapper.writeString(__out, ContractNumber__typeInfo, ContractNumber, ContractNumber__is_set);
       __typeMapper.writeObject(__out, CreatedBy__typeInfo, CreatedBy, CreatedBy__is_set);
       __typeMapper.writeString(__out, CreatedById__typeInfo, CreatedById, CreatedById__is_set);
       __typeMapper.writeObject(__out, CreatedDate__typeInfo, CreatedDate, CreatedDate__is_set);
       __typeMapper.writeString(__out, Description__typeInfo, Description, Description__is_set);
       __typeMapper.writeObject(__out, Discount__typeInfo, Discount, Discount__is_set);
       __typeMapper.writeObject(__out, EndDate__typeInfo, EndDate, EndDate__is_set);
       __typeMapper.writeObject(__out, Entitlements__typeInfo, Entitlements, Entitlements__is_set);
       __typeMapper.writeObject(__out, Events__typeInfo, Events, Events__is_set);
       __typeMapper.writeObject(__out, FeedSubscriptionsForEntity__typeInfo, FeedSubscriptionsForEntity, FeedSubscriptionsForEntity__is_set);
       __typeMapper.writeObject(__out, Feeds__typeInfo, Feeds, Feeds__is_set);
       __typeMapper.writeObject(__out, GrandTotal__typeInfo, GrandTotal, GrandTotal__is_set);
       __typeMapper.writeObject(__out, Histories__typeInfo, Histories, Histories__is_set);
       __typeMapper.writeObject(__out, IsDeleted__typeInfo, IsDeleted, IsDeleted__is_set);
       __typeMapper.writeObject(__out, LastModifiedBy__typeInfo, LastModifiedBy, LastModifiedBy__is_set);
       __typeMapper.writeString(__out, LastModifiedById__typeInfo, LastModifiedById, LastModifiedById__is_set);
       __typeMapper.writeObject(__out, LastModifiedDate__typeInfo, LastModifiedDate, LastModifiedDate__is_set);
       __typeMapper.writeObject(__out, LastReferencedDate__typeInfo, LastReferencedDate, LastReferencedDate__is_set);
       __typeMapper.writeObject(__out, LastViewedDate__typeInfo, LastViewedDate, LastViewedDate__is_set);
       __typeMapper.writeObject(__out, LineItemCount__typeInfo, LineItemCount, LineItemCount__is_set);
       __typeMapper.writeString(__out, Name__typeInfo, Name, Name__is_set);
       __typeMapper.writeObject(__out, Notes__typeInfo, Notes, Notes__is_set);
       __typeMapper.writeObject(__out, NotesAndAttachments__typeInfo, NotesAndAttachments, NotesAndAttachments__is_set);
       __typeMapper.writeObject(__out, OpenActivities__typeInfo, OpenActivities, OpenActivities__is_set);
       __typeMapper.writeObject(__out, Owner__typeInfo, Owner, Owner__is_set);
       __typeMapper.writeString(__out, OwnerId__typeInfo, OwnerId, OwnerId__is_set);
       __typeMapper.writeObject(__out, Pricebook2__typeInfo, Pricebook2, Pricebook2__is_set);
       __typeMapper.writeString(__out, Pricebook2Id__typeInfo, Pricebook2Id, Pricebook2Id__is_set);
       __typeMapper.writeObject(__out, ProcessInstances__typeInfo, ProcessInstances, ProcessInstances__is_set);
       __typeMapper.writeObject(__out, ProcessSteps__typeInfo, ProcessSteps, ProcessSteps__is_set);
       __typeMapper.writeString(__out, ShippingCity__typeInfo, ShippingCity, ShippingCity__is_set);
       __typeMapper.writeString(__out, ShippingCountry__typeInfo, ShippingCountry, ShippingCountry__is_set);
       __typeMapper.writeObject(__out, ShippingHandling__typeInfo, ShippingHandling, ShippingHandling__is_set);
       __typeMapper.writeObject(__out, ShippingLatitude__typeInfo, ShippingLatitude, ShippingLatitude__is_set);
       __typeMapper.writeObject(__out, ShippingLongitude__typeInfo, ShippingLongitude, ShippingLongitude__is_set);
       __typeMapper.writeString(__out, ShippingPostalCode__typeInfo, ShippingPostalCode, ShippingPostalCode__is_set);
       __typeMapper.writeString(__out, ShippingState__typeInfo, ShippingState, ShippingState__is_set);
       __typeMapper.writeString(__out, ShippingStreet__typeInfo, ShippingStreet, ShippingStreet__is_set);
       __typeMapper.writeString(__out, SpecialTerms__typeInfo, SpecialTerms, SpecialTerms__is_set);
       __typeMapper.writeObject(__out, StartDate__typeInfo, StartDate, StartDate__is_set);
       __typeMapper.writeString(__out, Status__typeInfo, Status, Status__is_set);
       __typeMapper.writeObject(__out, Subtotal__typeInfo, Subtotal, Subtotal__is_set);
       __typeMapper.writeObject(__out, SystemModstamp__typeInfo, SystemModstamp, SystemModstamp__is_set);
       __typeMapper.writeObject(__out, Tasks__typeInfo, Tasks, Tasks__is_set);
       __typeMapper.writeObject(__out, Tax__typeInfo, Tax, Tax__is_set);
       __typeMapper.writeObject(__out, Term__typeInfo, Term, Term__is_set);
       __typeMapper.writeObject(__out, TotalPrice__typeInfo, TotalPrice, TotalPrice__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        __in.peekTag();
        if (__typeMapper.isElement(__in, Account__typeInfo)) {
            setAccount((com.sforce.soap.enterprise.sobject.Account)__typeMapper.readObject(__in, Account__typeInfo, com.sforce.soap.enterprise.sobject.Account.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AccountId__typeInfo)) {
            setAccountId(__typeMapper.readString(__in, AccountId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivationDate__typeInfo)) {
            setActivationDate((java.util.Calendar)__typeMapper.readObject(__in, ActivationDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ActivityHistories__typeInfo)) {
            setActivityHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ActivityHistories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ApprovalStatus__typeInfo)) {
            setApprovalStatus(__typeMapper.readString(__in, ApprovalStatus__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, AttachedContentDocuments__typeInfo)) {
            setAttachedContentDocuments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, AttachedContentDocuments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Attachments__typeInfo)) {
            setAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Attachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingCity__typeInfo)) {
            setBillingCity(__typeMapper.readString(__in, BillingCity__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingCountry__typeInfo)) {
            setBillingCountry(__typeMapper.readString(__in, BillingCountry__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingLatitude__typeInfo)) {
            setBillingLatitude((java.lang.Double)__typeMapper.readObject(__in, BillingLatitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingLongitude__typeInfo)) {
            setBillingLongitude((java.lang.Double)__typeMapper.readObject(__in, BillingLongitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingPostalCode__typeInfo)) {
            setBillingPostalCode(__typeMapper.readString(__in, BillingPostalCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingState__typeInfo)) {
            setBillingState(__typeMapper.readString(__in, BillingState__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, BillingStreet__typeInfo)) {
            setBillingStreet(__typeMapper.readString(__in, BillingStreet__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CombinedAttachments__typeInfo)) {
            setCombinedAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, CombinedAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Contact__typeInfo)) {
            setContact((com.sforce.soap.enterprise.sobject.Contact)__typeMapper.readObject(__in, Contact__typeInfo, com.sforce.soap.enterprise.sobject.Contact.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContactId__typeInfo)) {
            setContactId(__typeMapper.readString(__in, ContactId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContractLineItems__typeInfo)) {
            setContractLineItems((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ContractLineItems__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ContractNumber__typeInfo)) {
            setContractNumber(__typeMapper.readString(__in, ContractNumber__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedBy__typeInfo)) {
            setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, CreatedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedById__typeInfo)) {
            setCreatedById(__typeMapper.readString(__in, CreatedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, CreatedDate__typeInfo)) {
            setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, CreatedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Description__typeInfo)) {
            setDescription(__typeMapper.readString(__in, Description__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Discount__typeInfo)) {
            setDiscount((java.lang.Double)__typeMapper.readObject(__in, Discount__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, EndDate__typeInfo)) {
            setEndDate((java.util.Calendar)__typeMapper.readObject(__in, EndDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Entitlements__typeInfo)) {
            setEntitlements((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Entitlements__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Events__typeInfo)) {
            setEvents((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Events__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, FeedSubscriptionsForEntity__typeInfo)) {
            setFeedSubscriptionsForEntity((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, FeedSubscriptionsForEntity__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Feeds__typeInfo)) {
            setFeeds((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Feeds__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, GrandTotal__typeInfo)) {
            setGrandTotal((java.lang.Double)__typeMapper.readObject(__in, GrandTotal__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Histories__typeInfo)) {
            setHistories((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Histories__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, IsDeleted__typeInfo)) {
            setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, IsDeleted__typeInfo, java.lang.Boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedBy__typeInfo)) {
            setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, LastModifiedBy__typeInfo, com.sforce.soap.enterprise.sobject.User.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedById__typeInfo)) {
            setLastModifiedById(__typeMapper.readString(__in, LastModifiedById__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastModifiedDate__typeInfo)) {
            setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, LastModifiedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastReferencedDate__typeInfo)) {
            setLastReferencedDate((java.util.Calendar)__typeMapper.readObject(__in, LastReferencedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LastViewedDate__typeInfo)) {
            setLastViewedDate((java.util.Calendar)__typeMapper.readObject(__in, LastViewedDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, LineItemCount__typeInfo)) {
            setLineItemCount((java.lang.Integer)__typeMapper.readObject(__in, LineItemCount__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Name__typeInfo)) {
            setName(__typeMapper.readString(__in, Name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Notes__typeInfo)) {
            setNotes((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Notes__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, NotesAndAttachments__typeInfo)) {
            setNotesAndAttachments((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, NotesAndAttachments__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OpenActivities__typeInfo)) {
            setOpenActivities((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, OpenActivities__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Owner__typeInfo)) {
            setOwner((com.sforce.soap.enterprise.sobject.Name)__typeMapper.readObject(__in, Owner__typeInfo, com.sforce.soap.enterprise.sobject.Name.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, OwnerId__typeInfo)) {
            setOwnerId(__typeMapper.readString(__in, OwnerId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Pricebook2__typeInfo)) {
            setPricebook2((com.sforce.soap.enterprise.sobject.Pricebook2)__typeMapper.readObject(__in, Pricebook2__typeInfo, com.sforce.soap.enterprise.sobject.Pricebook2.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Pricebook2Id__typeInfo)) {
            setPricebook2Id(__typeMapper.readString(__in, Pricebook2Id__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessInstances__typeInfo)) {
            setProcessInstances((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessInstances__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ProcessSteps__typeInfo)) {
            setProcessSteps((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, ProcessSteps__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingCity__typeInfo)) {
            setShippingCity(__typeMapper.readString(__in, ShippingCity__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingCountry__typeInfo)) {
            setShippingCountry(__typeMapper.readString(__in, ShippingCountry__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingHandling__typeInfo)) {
            setShippingHandling((java.lang.Double)__typeMapper.readObject(__in, ShippingHandling__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingLatitude__typeInfo)) {
            setShippingLatitude((java.lang.Double)__typeMapper.readObject(__in, ShippingLatitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingLongitude__typeInfo)) {
            setShippingLongitude((java.lang.Double)__typeMapper.readObject(__in, ShippingLongitude__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingPostalCode__typeInfo)) {
            setShippingPostalCode(__typeMapper.readString(__in, ShippingPostalCode__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingState__typeInfo)) {
            setShippingState(__typeMapper.readString(__in, ShippingState__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, ShippingStreet__typeInfo)) {
            setShippingStreet(__typeMapper.readString(__in, ShippingStreet__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SpecialTerms__typeInfo)) {
            setSpecialTerms(__typeMapper.readString(__in, SpecialTerms__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, StartDate__typeInfo)) {
            setStartDate((java.util.Calendar)__typeMapper.readObject(__in, StartDate__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Status__typeInfo)) {
            setStatus(__typeMapper.readString(__in, Status__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Subtotal__typeInfo)) {
            setSubtotal((java.lang.Double)__typeMapper.readObject(__in, Subtotal__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, SystemModstamp__typeInfo)) {
            setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, SystemModstamp__typeInfo, java.util.Calendar.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Tasks__typeInfo)) {
            setTasks((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, Tasks__typeInfo, com.sforce.soap.enterprise.QueryResult.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Tax__typeInfo)) {
            setTax((java.lang.Double)__typeMapper.readObject(__in, Tax__typeInfo, java.lang.Double.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, Term__typeInfo)) {
            setTerm((java.lang.Integer)__typeMapper.readObject(__in, Term__typeInfo, java.lang.Integer.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, TotalPrice__typeInfo)) {
            setTotalPrice((java.lang.Double)__typeMapper.readObject(__in, TotalPrice__typeInfo, java.lang.Double.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ServiceContract ");
      sb.append(super.toString());sb.append(" Account=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Account)+"'\n");
      sb.append(" AccountId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AccountId)+"'\n");
      sb.append(" ActivationDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ActivationDate)+"'\n");
      sb.append(" ActivityHistories=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ActivityHistories)+"'\n");
      sb.append(" ApprovalStatus=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ApprovalStatus)+"'\n");
      sb.append(" AttachedContentDocuments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(AttachedContentDocuments)+"'\n");
      sb.append(" Attachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Attachments)+"'\n");
      sb.append(" BillingCity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingCity)+"'\n");
      sb.append(" BillingCountry=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingCountry)+"'\n");
      sb.append(" BillingLatitude=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingLatitude)+"'\n");
      sb.append(" BillingLongitude=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingLongitude)+"'\n");
      sb.append(" BillingPostalCode=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingPostalCode)+"'\n");
      sb.append(" BillingState=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingState)+"'\n");
      sb.append(" BillingStreet=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(BillingStreet)+"'\n");
      sb.append(" CombinedAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CombinedAttachments)+"'\n");
      sb.append(" Contact=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Contact)+"'\n");
      sb.append(" ContactId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ContactId)+"'\n");
      sb.append(" ContractLineItems=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ContractLineItems)+"'\n");
      sb.append(" ContractNumber=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ContractNumber)+"'\n");
      sb.append(" CreatedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedBy)+"'\n");
      sb.append(" CreatedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedById)+"'\n");
      sb.append(" CreatedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(CreatedDate)+"'\n");
      sb.append(" Description=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Description)+"'\n");
      sb.append(" Discount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Discount)+"'\n");
      sb.append(" EndDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(EndDate)+"'\n");
      sb.append(" Entitlements=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Entitlements)+"'\n");
      sb.append(" Events=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Events)+"'\n");
      sb.append(" FeedSubscriptionsForEntity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(FeedSubscriptionsForEntity)+"'\n");
      sb.append(" Feeds=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Feeds)+"'\n");
      sb.append(" GrandTotal=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(GrandTotal)+"'\n");
      sb.append(" Histories=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Histories)+"'\n");
      sb.append(" IsDeleted=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(IsDeleted)+"'\n");
      sb.append(" LastModifiedBy=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedBy)+"'\n");
      sb.append(" LastModifiedById=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedById)+"'\n");
      sb.append(" LastModifiedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastModifiedDate)+"'\n");
      sb.append(" LastReferencedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastReferencedDate)+"'\n");
      sb.append(" LastViewedDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LastViewedDate)+"'\n");
      sb.append(" LineItemCount=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(LineItemCount)+"'\n");
      sb.append(" Name=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Name)+"'\n");
      sb.append(" Notes=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Notes)+"'\n");
      sb.append(" NotesAndAttachments=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(NotesAndAttachments)+"'\n");
      sb.append(" OpenActivities=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OpenActivities)+"'\n");
      sb.append(" Owner=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Owner)+"'\n");
      sb.append(" OwnerId=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(OwnerId)+"'\n");
      sb.append(" Pricebook2=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Pricebook2)+"'\n");
      sb.append(" Pricebook2Id=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Pricebook2Id)+"'\n");
      sb.append(" ProcessInstances=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessInstances)+"'\n");
      sb.append(" ProcessSteps=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ProcessSteps)+"'\n");
      sb.append(" ShippingCity=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingCity)+"'\n");
      sb.append(" ShippingCountry=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingCountry)+"'\n");
      sb.append(" ShippingHandling=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingHandling)+"'\n");
      sb.append(" ShippingLatitude=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingLatitude)+"'\n");
      sb.append(" ShippingLongitude=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingLongitude)+"'\n");
      sb.append(" ShippingPostalCode=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingPostalCode)+"'\n");
      sb.append(" ShippingState=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingState)+"'\n");
      sb.append(" ShippingStreet=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(ShippingStreet)+"'\n");
      sb.append(" SpecialTerms=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SpecialTerms)+"'\n");
      sb.append(" StartDate=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(StartDate)+"'\n");
      sb.append(" Status=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Status)+"'\n");
      sb.append(" Subtotal=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Subtotal)+"'\n");
      sb.append(" SystemModstamp=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(SystemModstamp)+"'\n");
      sb.append(" Tasks=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Tasks)+"'\n");
      sb.append(" Tax=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Tax)+"'\n");
      sb.append(" Term=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(Term)+"'\n");
      sb.append(" TotalPrice=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(TotalPrice)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
